### ISSUE TITLE
Support for AWS Kinesis

### ISSUE THREAD

**Issue by GrahamCampbell** [async-aws/aws#1003]
I'd be happy to do most of this, if I can had some hand holding. 🤣

**Comment by jderusse** [comment]
That would be awesome. Here is a good start to add a new client: https://async-aws.com/contribute/generate.html#creating-a-new-client

I realize that adding a new client is not easy (see https://github.com/async-aws/aws/pull/999)
Maybe we should setup the glue to add the client by our own and let contributors adding the operations on top of it 
/cc @Nyholm

**Comment by Nyholm** [comment]
There are many steps, but all of them are tested. So if the CI is green, then everything will work. 

@GrahamCampbell try start and feel free to give up super easily if the documentation is not enough. (If you give up, please name an operation you would like to have)

**Comment by GrahamCampbell** [comment]
Thanks both. I'll look at this soon. :)
