### ISSUE TITLE
[SQS] Batch send support

### ISSUE THREAD

**Issue by atymic** [async-aws/aws#1032]
Hey :)

Do you support batch sending through SQS? Looked at the code and it seems not.

**Comment by jderusse** [comment]
Hello, We do not support `SendMessageBatch`, but we will be happy to merge a PR that add it:

See how to add a new operation: https://async-aws.com/contribute/generate.html#creating-a-new-client-operation

**Comment by jderusse** [comment]
Closing this issue, feel free to open a PR to add the missing operation
