### ISSUE TITLE
[STS] Support for STS_REGIONAL_ENDPOINTS

### ISSUE THREAD

**Issue by deleugpn** [async-aws/aws#1061]
According to STS docs, we can send into the StsClient a `sts_regional_endpoints` parameter (ref: https://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.Sts.StsClient.html#___construct). When using async-aws, I get the following error:

```
PHP Fatal error:  Uncaught AsyncAws\Core\Exception\InvalidArgument: Invalid option(s) "sts_regional_endpoints", "version" passed to "AsyncAws\Core\Configuration::AsyncAws\Core\Configuration::create".  in /codebuild/output/src509504300/src/codestar-connections.eu-west-1.amazonaws.com/git-http/aaaaaa/eu-west-1/1160e2b0-edbc-41f4-a87a-f1bb2ec0f8bd/brefphp/bref/vendor/async-aws/core/src/Configuration.php:94
372
```

https://github.com/aws/aws-sdk-php/blob/master/src/Sts/StsClient.php#L55

**Comment by jderusse** [comment]
Hey, what's you use case for using this parameter?

When reading the code of the official AWS SDK, this parameter is linked to "Legacy endpoints". I'm not familiar with this, but it looks like a backward compatibility layer for AWS, and I'm not sure we should backport this in AsyncAws

**Comment by deleugpn** [comment]
Legacy endpoints are the ones used by default and kept for backward compatibility. This parameter instructs the SDK to use region-specific endpoints instead of a single, global, centralized endpoint. 
Some new AWS Regions don't support the legacy endpoints and without this parameter they can't be used when assuming role.

Bref use-case is that we're running 1 AWS CodeBuild to compile PHP and export the layers. We do this in 1 AWS Region only. We then need to publish the layers on every AWS region. That means we need to assume role into the Layers account and make cross-region API calls. When attempting to publish on regions like Cape Town, Milan and Barhain the legacy (default) endpoints don't work. We have to opt-in to region-specific endpoints to be able to authenticate there.

Reference: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_enable-regions.html

**Comment by jderusse** [comment]
Well, AsyncAws use region-specific endpoints for STS when you provide a region.

https://github.com/async-aws/aws/blob/5f292f37531324d9ac4c32114c7ff569e31ba153/src/Core/src/Sts/StsClient.php#L138-L230

If I understand your use-case, some region does not supports "regional endpoints", and the `sts_regional_endpoints` parameters allowed you to switch to the global endpoint. right?

**Comment by deleugpn** [comment]
> some region does not supports "regional endpoints"

No, every region supports regional endpoints. Some regions don't support authentication via global endpoints.

From what you linked and what you explained, perhaps AsyncAWS is already doing the recommended approach by default, which means Bref use-case should probably work. I'll work on releasing https://github.com/brefphp/bref/pull/993 with Napoli on Wednesday and I'll give this a try again to see if I remember anything else. It could be that I just assumed AsyncAws was doing exactly what the official SDK is doing and never really "just tried it". If you don't mind I'll keep this open until Wednesday.

**Comment by Nyholm** [comment]
So, how did it go? 

What is the status on this issue?

**Comment by stof** [comment]
@deleugpn any news here ?

**Comment by stof** [comment]
AsyncAws is using the regional endpoint as soon as a region is provided either as part of the client configuration as through the `@region` setting of the input. It does not require a `sts_regional_endpoints` parameter to use the non-legacy endpoint (the legacy endpoint is used only when no region is provided at all).

So I'm closing this as it is supported.
