### ISSUE TITLE
[S3] Support for stream wrappers

### ISSUE THREAD

**Issue by faizanakram99** [async-aws/aws#1063]
Official AWS SDK client for PHP supports stream wrapper for S3 Client.

https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/s3-stream-wrapper.html

Is there something similar for async-aws/s3 ? 
(I couldn't find it)

**Comment by faizanakram99** [comment]
It is easy to swap base file path with a stream wrapper in a legacy application.

`fopen`, `file_get_contents`, etc all work out of the box with almost no change in codebase.

**Comment by stof** [comment]
to be, this should be handled by using the Flysystem stream wrapper with their adapter for async-aws/s3 instead of writing our own stream wrapper here.
@jderusse I suggest closing this issue.
