### ISSUE TITLE
Uncaught Error: Class 'AsyncAws\SecretManager\SecretManagerClient' not found

### ISSUE THREAD

**Issue by albaedu** [async-aws/aws#1066]
Hello. I created a new empty file and pasted:

```
<?php

require('/opt/vendor/autoload.php');
$secretManager = new AsyncAws\SecretManager\SecretManagerClient([
	'version' => 'latest',
	'region' => $_ENV["AWS_REGION"],
]);

var_dump($secretManager);

```
And says:

`Uncaught Error: Class 'AsyncAws\SecretManager\SecretManagerClient' not found`

Same result with code:

```
use AsyncAws\SecretManager\SecretManagerClient;
$secretManager = new SecretManagerClient();
var_dump($secretManager);
```

Content of composer.json:

```
{
    "require": {
        "async-aws/secrets-manager": "^0.1.0"
    }
}
```
var_dump(file_get_contents("/opt/vendor/autoload.php")); gives right content:

```
<?php
// autoload.php @generated by Composer

require_once __DIR__ . '/composer/autoload_real.php';

return ComposerAutoloaderInit012428fa155cbf5ab45fc020ebe45b75: :getLoader();
```

**Comment by jderusse** [comment]
did you run `composer update`? 
are you sure that the `composer.json` is located in `/opt/composer.json`?
can you check the structure of `/opt/vendor` and check that the folder `async-aws` exists and contains the expected files.

**Comment by albaedu** [comment]
Hello. The folder async-aws exists in /opt/vendor and has the expected files. I send attached the composer package
[test-099c6381-34de-4e65-83fc-28747f46fda4.zip](https://github.com/async-aws/aws/files/7006200/test-099c6381-34de-4e65-83fc-28747f46fda4.zip)

**Comment by jderusse** [comment]
You have a typo: it's `SecretsManager` with a `s` at the end of secrets.

Could you check if the typo was in our doc? if yes, please, open a pull request to fix ir

**Comment by albaedu** [comment]
Hello. Thanks. Yes in the docs always says use AsyncAws\SecretManager\SecretManagerClient; and similar
