### ISSUE TITLE
Optional value required when creating secret in SecretsManager

### ISSUE THREAD

**Issue by sunkan** [async-aws/aws#1069]
When creating/updating a secret in the secrets manager your required to specify a `ClientRequestToken` but the generated client says that the value is optional. 

And if you don't add it the api will throw `InvalidRequestException "You must provide a ClientRequestToken value. We recommend a UUID-type value."`

So is there any way to modify the specification before we generate the code so that we can either generate the `ClientRequestToken` or mark it as required?

The [aws documentation](https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_CreateSecret.html#SecretsManager-CreateSecret-request-ClientRequestToken)  does say that it's optional because they automatically generate the value in there SDK

**Comment by jderusse** [comment]
the docs says

> (Optional) If you include SecretString or SecretBinary,

Did you provide a `SecretString` when you omitted the  `ClientRequestToken`?

**Comment by sunkan** [comment]
Yes.

This was the code that failed
```
$input['SecretId'] = 'key';
$input['SecretString'] = 'value';
$client->createSecret($input);
```

But the documentation have this notice 

> If you use the AWS CLI or one of the AWS SDK to call this operation, then you can leave this parameter empty. The CLI or SDK  generates a random UUID for you and includes it as the value for this parameter in the request. If you don't use the SDK and instead generate a raw HTTP request to the Secrets Manager service endpoint, then you must generate a ClientRequestToken yourself for the new version and include the value in the request.

**Comment by jderusse** [comment]
good catch, the official SDK have a special handling for this property and don't follow the specs.

I'll take care of this once back from vacations

**Comment by jderusse** [comment]
ohh.. it's something that is defined in specs: https://github.com/aws/aws-sdk-php/blob/c2063c78310b45e378f1bdad9fe6e9191f36439c/src/data/secretsmanager/2017-10-17/api-2.json#L399
And the related code than handle it: https://github.com/aws/aws-sdk-php/blob/15f6b434b92826a321191bf5b72820934d970580/src/IdempotencyTokenMiddleware.php
