### ISSUE TITLE
how to set a http connect_timeout when upload file?

### ISSUE THREAD

**Issue by everyx** [async-aws/aws#1074]
I want set a connect timeout whne upload file, how to do this? or what is the defautl value? thanks. :)

**Comment by Nyholm** [comment]
Excellent question!

You can control the timeout (but not "connect timeout") by using the `resolve()` method. See https://async-aws.com/features/async.html#using-resolve-function

To really set the connect timeout, you need to create a HTTP Client yourself. Something like (not tested): 

```php
use Symfony\Component\HttpClient\CurlHttpClient;
use AsyncAws\S3\S3Client;

$httpClient = new CurlHttpClient([
  'extra' => ['curl' => [
     \CURLOPT_CONNECTTIMEOUT_MS => 2000,
  ]]
]);

$s3Client = new S3Client([], null, $httpClient);
```
