### ISSUE TITLE
Support for AppSync

### ISSUE THREAD

**Issue by jordihendrix** [async-aws/aws#1101]
I should be able to get most of this done myself, might need a little bit of instruction on how to implement the tests.

Will add a (Draft/WIP) PR with what I've got so far.

**Comment by jordihendrix** [comment]
Still need to fix one or two things and add some documentation, but I could use a little bit of help on the "Generated output not changed" check. I don't really understand why it's failing as I'm pretty sure I just followed the instructions on the site. Also, if I run the `./generate --all` (as suggested by the check output) I end up with changes in tons of files in every service, and it also adds AppSync operations I don't need. Am I doing something wrong here?

**Comment by Nyholm** [comment]
Are you happy with the [AppSync](https://github.com/async-aws/app-sync) client? Should we tag a release?
