### ISSUE TITLE
Provide flysystem v2/v3 compatible version of`async-aws/flysystem-s3` 

### ISSUE THREAD

**Issue by GrahamCampbell** [async-aws/aws#1164]
NB I'm creating this to track this, not because I expect anyone to implement it. I may get around to this, and I also may never get around to it. This could be a good first issue for a first time contributor who is familiar with flysystem. :)

**Comment by jderusse** [comment]
There is an official adapter for flysystem v2/v3 => https://github.com/thephpleague/flysystem-async-aws-s3

Did I missed something?

**Comment by GrahamCampbell** [comment]
Well, that was easy. ;)
