### ISSUE TITLE
Provide Laravel 9 compatible version of `async-aws/illuminate-flysystem`

### ISSUE THREAD

**Issue by GrahamCampbell** [async-aws/aws#1165]
Depends on https://github.com/async-aws/aws/issues/1164.

---

NB I'm creating this to track this, not because I expect anyone to implement it. I may get around to this, and I also may never get around to it. This could be a good first issue for a first time contributor who is familiar with flysystem. :)

**Comment by stof** [comment]
@jderusse with the deprecation of `async-aws/flysystem-s3` in favor of the core adapter of Flysystem 2+, we should also deprecate that package instead of upgrading it IMO.

**Comment by GrahamCampbell** [comment]
Agreed.

**Comment by jderusse** [comment]
I'm not familiar with Laravel ecosystem. What package should we recommend for replacement?

**Comment by GrahamCampbell** [comment]
I don't think anyone has created one. I guess there's little demand for it. `async-aws/illuminate-filesystem` also has basically no installs. ;)
