### ISSUE TITLE
Provide Laravel 9 compatible version of `async-aws/illuminate-mail`

### ISSUE THREAD

**Issue by GrahamCampbell** [async-aws/aws#1166]
Laravel 9 now uses Symfony Mailer.

---

NB I'm creating this to track this, not because I expect anyone to implement it. I may get around to this, and I also may never get around to it. This could be a good first issue for a first time contributor who is familiar with Symfony Mailer. :)

**Comment by stof** [comment]
Given that `symfony/amazon-mailer` exists, that implements Symfony Mailer transports on top of async-aws/ses, is there anything to do here ?

**Comment by GrahamCampbell** [comment]
Probably not a lot to do, yeh.

**Comment by stof** [comment]
@jderusse should we deprecate the `async-aws/illuminate-mail` package ? It is barely installed: https://packagist.org/packages/async-aws/illuminate-mail/stats
And it only supports Laravel 8 and older, which are EOL.

**Comment by stof** [comment]
@jderusse while you are working on deprecating packages, this issue could be one to handle as well.
