### ISSUE TITLE
The BC Checks CI setup reports weird issues

### ISSUE THREAD

**Issue by stof** [async-aws/aws#1169]
The BC checks for async-aws/illluminate-queue are currently failing, saying that some `Illuminate\Queue` methods are being removed. Those are not BC break in the async-aws package, but in Laravel. So it looks like something is weird in the configuration of the CI.

**Comment by jderusse** [comment]
hmm.. Actually, `AsyncAwsSqsQueue` extends `Illuminate\Queue\Queue` and `AsyncAwsSqsJob` extends `Illuminate\Queue\Jobs\Job`

When allowing `illuminate/queue": "... || ^8.0` in our dependencies, we broke the BC of async-aws.

I'm not sure how to fix this one. Any suggestion?

**Comment by stof** [comment]
oh, I missed that.

I would say, make it a new semver major version of this package then (that is, 0.2.0).

**Comment by GrahamCampbell** [comment]
I think this is getting fixed today, so can be closed later today, assuming the last change to make works.

**Comment by GrahamCampbell** [comment]
Yep, fixed. This issue can be closed @jderusse.
