### ISSUE TITLE
S3Client getObjectUrl equivalent in async aws

### ISSUE THREAD

**Issue by rmikalkenas** [async-aws/aws#1231]
Is there a way to get s3 object url, like it is in `S3Client::getObjectUrl`?

Basically I need an unsigned url of an object

**Comment by jderusse** [comment]
If you want a public URL you need to make your object public (https://docs.aws.amazon.com/AmazonS3/latest/userguide/acl-overview.html)

If you want providing temporary access to an object, you need can use the `SimpleS3Client::getPresignedUrl` method

**Comment by rmikalkenas** [comment]
Hm, sounds a bit of a overhead to install additional dependency just for a single method.. For a presigned url it's pretty easy, since `S3Client::presign` method is public. But `SimpleS3Client::getUrl` uses `getEndpoint` method which is protected and cannot be called from outside of class scope.
I kind of understand the idea behind `SimpleS3Client`, but IMO separate library adds additional load/complexity not only for a developer, but for maintainer as well..
Other than that, thanks for your input @jderusse ! I will probably think of other approaches how to retrieve a public bucket's object url

**Comment by jderusse** [comment]
actually, I can't agree.

Putting everything in the same place is the strategy used by the official AWS SDK, which leads to a HUGE package with thousands of versions, poor performance, and waste of resources (bandwidth, memory, CPU)

The S3 client provides methods to interact with the AWS S3 API in **the way defined by AWS**.
The SimpleS3 client provides an unofficial way to perform the same things but with a better DX / pleasant interfaces.

If you don't want to install the `SimpleS3Client`, you can reuse the code of the `getPresignedUrl` in your own application.

```
        $request = new GetObjectRequest([
            'Bucket' => $bucket,
            'Key' => $key,
        ]);

        $url = $s3Client->presign($request, new \DateTimeImmutable('+2 hours'));
```

**Comment by rmikalkenas** [comment]
@jderusse thanks for clear explanation of multiple packages, that makes perfectly sense!

Closing the issue, since I solved it
