### ISSUE TITLE
No mechanism to disable HTTP retries

### ISSUE THREAD

**Issue by GrahamCampbell** [async-aws/aws#1234]
There's no mechanism to instantiate a client without retries. The bug with the symfony retry client is really (https://github.com/async-aws/aws/issues/1128) kicking me hard, with 10s of thousands of failures every day. Moreover, when I'm performing lots of requests in parallel, it is not efficient when there is a failure, for each to synchronously re-try. For that reason, I feel the best approach for my is to turn off retries, and manage that higher up the stack, so I can retry large batches of requests at once.

**Comment by GrahamCampbell** [comment]
Any thoughts here @jderusse?

**Comment by nicolas-grekas** [comment]
But ideally we'd better understand and solve #1128

**Comment by GrahamCampbell** [comment]
I would like to get to the bottom of that, but I can't allocate the time right now. I'd need to clear a day to work that stuff out.
