### ISSUE TITLE
Catch php warning when host is not complete

### ISSUE THREAD

**Issue by shyim** [async-aws/aws#1258]
```
In Request.php line 128:
                                         
  [ErrorException]                       
  Warning: Undefined array key "scheme"  
                                         

Exception trace:
  at /Users/shyim/Code/sw6/vendor/async-aws/core/src/Request.php:128
```

I used as endpoint just `localhost:9000`, this triggers a warning because the scheme is missing. Maybe scheme should be required or has an fallback to something 🤔

**Comment by GrahamCampbell** [comment]
Probably we should add some validation to reject the bad config, at source.

**Comment by stof** [comment]
Fixed in https://github.com/async-aws/aws/pull/1504
