### ISSUE TITLE
Receive Empty Messages SQS

### ISSUE THREAD

**Issue by alaglil** [async-aws/aws#1285]
I use FIFO Queue and , I get an empty result in receiveMessage function, thanks for your help
```
 $result = $sqs->sendMessage(new SendMessageRequest([
                    'QueueUrl' => $queueUrl,
                    'DelaySeconds' => 0,
                    'MessageGroupId' =>  'report',
                    'MessageDeduplicationId'  =>  $clientId
                    'MessageBody' => 'mesage test',
];
```
      $result = $sqs->receiveMessage(new ReceiveMessageRequest([
            'QueueUrl' => $queueUrl,
            'AttributeNames' => [MessageSystemAttributeName::MESSAGE_GROUP_ID, MessageSystemAttributeName::MESSAGE_DEDUPLICATION_ID],
            'WaitTimeSeconds' => 20,
            'VisibilityTimeout' => 20,
            'MaxNumberOfMessages' => 1, 
            'MessageAttributeNames' => ['All']
        ]));

```

**Comment by alaglil** [comment]
I found the problem I have a lambda SQS trigger function which calls a php endpoint which has its role of receiving the messages, as indicated above,
the lambda function deletes the messages before it arrives in the endpoint I'm a little lost what is the best way to call the receiveMessages function automaticly and process them?

**Comment by DhwanishShah** [comment]
Hi, i want to contribute in this project.Please assign me in this project to work in this issue. @alaglil @markdorison @shouze @j0k3r @ddeboer

**Comment by Jehan-h20220012** [comment]
I want to contribute to solve this issue, please let me contribute as it would help in my acedamics and your problem will be solved.

**Comment by jderusse** [comment]
I'm closing the issue because there is no bug in the SDK.
The purpose of SQS message is to be delivered once to a single consumer, If you have concurrent applications (lambda + PHP) that consumes the same queues, you can not predict which one will get the message.
