### ISSUE TITLE
How to mock a waiter ?

### ISSUE THREAD

**Issue by GromNaN** [async-aws/aws#1306]
I'd like to mock calls to `S3Client::objectExists`. This method returns a `Waiter` instead of a `Result`.
- `ResultMockFactory` cannot be used for this object type, as described in the [doc](https://async-aws.com/features/tests.html).
- I cannot mock the `Waiter` class because the method `wait` is final.

Code to test:
```php
    $s3Client->objectExists([
        'Bucket' => $bucket,
        'Key' => $key,
    ])->wait();
```

**Comment by GromNaN** [comment]
Finally I used integration tests with localstack. I'm not sure mocking helpers was a good idea.
Closing this issue. Can be reopen if you believe this method should be mockable.

**Comment by Syndesi** [comment]
I have run into the same issue; the implementation of Waiters has not significantly changed in the meantime.

While integration tests are an alternative - which are also used in this library - being able to mock Waiters away would be awesome :D

**Comment by Syndesi** [comment]
I extracted the `isSuccess()` call of the Waiter into a separate class, which I can mock:
```php
/**
 * @codeCoverageIgnore
 */
class S3ClientWrapper
{
    public function getIsSuccessFromObjectExistsWaiter(ObjectExistsWaiter $objectExistsWaiter): bool
    {
        return $objectExistsWaiter->isSuccess();
    }
}
```
Which can then be used like this:
```php
class S3Service
{
    public function __construct(
        private S3Client $s3Client,
        private S3ClientWrapper $s3ClientWrapper,
    ) {
    }
    public function existsFile(): bool
    {
        $objectExistsWaiter = $this->s3Client->objectExists([
            'Bucket' => 'some-bucket',
            'Key' => 'some-key',
        ]);
        return $this->s3ClientWrapper->getIsSuccessFromObjectExistsWaiter($objectExistsWaiter);
    }
}
```
And in tests I mock my wrapper, instead of the Waiter (using Prophecy):
```php
public function testExistsFile(): void
{
    $objectExistsWaiter = $this->prophesize(ObjectExistsWaiter::class)->reveal();

    $s3Client = $this->prophesize(S3Client::class);
    $s3Client->objectExists(Argument::is([
        'Bucket' => 'some-bucket',
        'Key' => 'some-key',
    ]))->shouldBeCalledOnce()->willReturn($objectExistsWaiter);

    $s3ClientWrapper = $this->prophesize(S3ClientWrapper::class);
    $s3ClientWrapper->getIsSuccessFromObjectExistsWaiter(Argument::is($objectExistsWaiter))->shouldBeCalledOnce()->willReturn(true);

    $s3Service = new S3Service(
        $s3Client->reveal(),
        $s3ClientWrapper->reveal()
    );

    $output = $s3Service->existsFile();
    $this->assertSame(true, $output);
}
```
It is not ideal, but it moves the issue from my production code to a place where it is not as problematic.
