### ISSUE TITLE
Release `async-aws/iam`

### ISSUE THREAD

**Issue by nealio82** [async-aws/aws#1351]
Can I get a release of `async-aws/iam` please? I added the `1.3.0` notes to the changelog as part of my last PR (https://github.com/async-aws/aws/blob/master/src/Service/Iam/CHANGELOG.md) - although now I'm worried that I might have done it a bit too pre-emptively? 😟

**Comment by jderusse** [comment]
done. 
Thanks for your contribution

**Comment by nealio82** [comment]
Thank you @jderusse  :)
