### ISSUE TITLE
Release `async-aws/iam` `1.4.0` | Fix `async-aws/iam` `1.3.0`

### ISSUE THREAD

**Issue by nealio82** [async-aws/aws#1358]
Can we get a tagged release of `async-aws/iam` `1.4.0` please?

Also, the `1.3.0` tag appears to point to the wrong commit. It currently points to `074ecc2a`, which doesn't include any of the changes made in `4568b205`. Is it possible / pain-free to re-tag, or will `1.3.1` need to be added instead? At the moment I'm requiring `dev-master` as a workaround

Thanks :)

**Comment by nealio82** [comment]
I forgot to point out above that if `1.4.0` is released, I won't need `1.3.0` to be fixed; depends on what you want to do for completeness / correctness 😝

**Comment by jderusse** [comment]
changelog fix, release 1.4.0 done
