### ISSUE TITLE
Generate large Zip from s3 files and save it back to s3

### ISSUE THREAD

**Issue by thedomeffm** [async-aws/aws#1411]
**My goal: My users can upload hundreds/thousands of images and can select all/some of them for an Zip download.**

My stack:
- Symfony
- [Flysystem Bundle](https://github.com/thephpleague/flysystem-bundle)
- [async-aws s3 adapter](https://flysystem.thephpleague.com/docs/adapter/async-aws-s3/)

The upload part is easy and already done.

My thoughts were that I use the messenger queue to generate a Zip and use `publicUrl`.
I wanted to use the ZipStream library (https://maennchen.dev/ZipStream-PHP/guide/StreamOutput.html) to avoid allocating to much diskspace while Zip generation.
The example in the docs of the library uses the original aws SDK and uses the `registerStreamWrapper` which is not supported in async-aws.

I could use `tmpfile()` as my output stream, but that would allocate diskspace,
or I could use `fopen('php://memory', 'w+')`, but that would allocate my memory.

Both options are bad for small servers like mine.

Is there a way you know how I could directly stream my images into the ZipStream back into S3 via your s3 client without allocating tons of diskspace/memory?

_I've also asked the maintainer of the ZipStream library see here: https://github.com/maennchen/ZipStream-PHP/issues/264#issuecomment-1564189084_
_He said I should propose a new method in the FlySystem, but I think the s3client is missing the proper methods too, or am I wrong?_

My current code with different ways of wasting my server resources either disk space or memory.
```php
// $uploadStorage is the Flysystem FilesystemOperator, but would work with the S3Client or SimpleS3Client exactly the same.

$uploads = $this->getUploadsOfUser();

$tempStream = fopen('php://memory', 'w+'); // memory allocation
$tempStream = tmpfile(); // disk allocation

$zipStream = new ZipStream(
    outputStream: $tempStream,
    enableZip64: true,
    outputName: 'test.zip',
);

foreach ($uploads as $upload) {
    $zipStream->addFileFromStream(
        fileName: $upload->originalUserFileName,
        stream: $uploadStorage->readStream($upload->getOriginalFilePath())
    );
}
$zipStream->finish();

$uploadStorage->writeStream('test.zip', $tempStream);
fclose($tempStream);
```

**Comment by jderusse** [comment]
I've no idea how ZipStream work.

But you can stream either:
- response reading: https://async-aws.com/clients/s3.html#download-files
- request writing: https://async-aws.com/clients/s3.html#upload-files

Let me know if you discover an issue/bug in the implementation of AsyncAws
