### ISSUE TITLE
SNS Client - Listing Topics

### ISSUE THREAD

**Issue by Ferror** [async-aws/aws#1442]
I have a use case where I need to list the SNS topics. Current SnsClient does not provide such functionality.

Would you be open to adding such functionality? I can provide the PR 😄 but I wanted to ensure that it wasn't added by design.

**Comment by jderusse** [comment]
Yes, we are totally open to new operations. 
To provide light clients, we provide only a few operations, but if someone has a use case for a new operation, we accept it automatically.

Here is the documentation to add a new operation: https://async-aws.com/contribute/generate.html#creating-a-new-client-operation
