### ISSUE TITLE
Update Item using async-aws DynamoDB is missing or what?

### ISSUE THREAD

**Issue by hassaan-dev** [async-aws/aws#1563]
Hi,

I was reading the documentation of [async-aws/dynamo-db](https://async-aws.com/clients/dynamodb.html) and found **Updating Item/Document** looks missing there. Is this supported? If yes, then is there any documentation available that I can follow?

**Comment by GrahamCampbell** [comment]
Not missing. Yes, https://github.com/async-aws/aws/blob/master/src/Service/DynamoDb/src/DynamoDbClient.php#L912-L963 has everything you need.

**Comment by hassaan-dev** [comment]
Thank you for your response.
Don't you think, this should have inside examples at [this page](https://async-aws.com/clients/dynamodb.html) as may be other people also need help for this as this is very common operation.
