### ISSUE TITLE
DynamoDB binary value encoding inconsistency

### ISSUE THREAD

**Issue by GrahamCampbell** [async-aws/aws#1564]
In requests, one passes the raw binary string `['B' => 'foo bar baz']`, but in responses, `->getB()` is base64 encoded. This feels like a bug to me (though will need a major version bump to "fix", so as to not break stuff for people).

**Comment by jderusse** [comment]
Indeed, there is a bug in the generated code for result objects: 
objects inside lists are not properly parsed, and the logic about decoding is skipped

Current code is
```
        $items = [];
        foreach ($json as $name => $value) {
            $items[(string) $name] = AttributeValue::create($value);
        }

        return $items;
```

instead of 
```
        $items = [];
        foreach ($json as $name => $value) {
            $items[(string) $name] = AttributeValue::create([
                'S' => $value['S'] ?? null,
                'N' => $value['N'] ?? null,
                'B' => isset($value['N']) ? base64_decode($value['N']) : null,
                // ...
            ]);
        }

        return $items;
```
