### ISSUE TITLE
DynamoDB query not refecting results with ExclusiveStartKey

### ISSUE THREAD

**Issue by hassaan-dev** [async-aws/aws#1579]
Hi,

I am using query to find the records from `Index`. This is working fine But I put next `ExclusiveStartKey` into my next query, I don't seen records reflection. I am assuming this is issue of `async-aws/dynamo-db` library.

Results are same as before `ExclusiveStartKey`

**Query 1**

```
{
    "TableName": "logs",
    "IndexName": "user_id-index",
    "KeyConditions": {
        "user_id": {
            "AttributeValueList": [
                {
                    "S": "123"
                }
            ],
            "ComparisonOperator": "EQ"
        }
    },
    "ScanIndexForward": false,
    "Limit": 3
}
```

**Query 2  _with `ExclusiveStartKey`_**

```
{
    "TableName": "logs",
    "IndexName": "user_id-index",
    "KeyConditions": {
        "user_id": {
            "AttributeValueList": [
                {
                    "S": "123"
                }
            ],
            "ComparisonOperator": "EQ"
        }
    },
    "ScanIndexForward": false,
    "Limit": 3,
    "ExclusiveStartKey": {
        "id": {
            "AsyncAws\\DynamoDb\\ValueObject\\AttributeValue": "abc"
        },
        "user_id": {
            "AsyncAws\\DynamoDb\\ValueObject\\AttributeValue": "123"
        },
        "created_at": {
            "AsyncAws\\DynamoDb\\ValueObject\\AttributeValue": "2023-09-13T09:14:58+0000"
        }
    }
}
```

**Comment by hassaan-dev** [comment]
Issue is confirmed again, I have **35 matching records** from `Index`.
I run while loop on this, On first 4 requests, I get all matching 35 recording via `getItems` instead of limit `10` and on 5th request. I got following 400 error

>Code:    ValidationException
>Message: The provided starting key is invalid


Another thing I notices, I got same value of `getLastEvaluatedKey` 2 times and an other same value of `getLastEvaluatedKey` 2 times.

**Comment by hassaan-dev** [comment]
I switched to `aws/aws-sdk-php` and paging is working fine for me now. Its confirmed that the issue is only with `async-aws/dynamo-db`

**Comment by jderusse** [comment]
The output `Query 2 ` looks strange (The FQDN in ExclusiveStartKey)
Could you please provide the code you used with when calling the `query` method?

**Comment by hassaan-dev** [comment]
I used below code for _`Query 2`_ @jderusse 

```
if (!empty($lastEvaluatedKey)) {
    foreach ($lastEvaluatedKey as $key => $val) {
        $conditionStartKey[$key] = ['S' => $val];
    }
}
```

> There was no error but results not reflecting. 


Query 3 _with `ExclusiveStartKey`_

```
{
    "TableName": "logs",
    "IndexName": "user_id-index",
    "KeyConditions": {
        "user_id": {
            "AttributeValueList": [
                {
                    "S": "123"
                }
            ],
            "ComparisonOperator": "EQ"
        }
    },
    "ScanIndexForward": false,
    "Limit": 3,
    "ExclusiveStartKey": {
        "id": "abc",
        "user_id": "123",
        "created_at": "2023-09-13T09:14:58+0000"
    }
}
```

Error
> "errorMessage": "AsyncAws\\DynamoDb\\ValueObject\\AttributeValue::__construct(): Argument #1 ($input) must be of type array, string given, called in /var/task/vendor/async-aws/dynamo-db/src/ValueObject/AttributeValue.php on line 122"



Query 4 _with `ExclusiveStartKey`_ (Final Query working with `aws/aws-sdk-php`)

```
{
    "TableName": "logs",
    "IndexName": "user_id-index",
    "KeyConditions": {
        "user_id": {
            "AttributeValueList": [
                {
                    "S": "123"
                }
            ],
            "ComparisonOperator": "EQ"
        }
    },
    "ScanIndexForward": false,
    "Limit": 3,
    "ExclusiveStartKey": {
        "id": {
            "S": "abc"
        },
        "user_id": {
            "S": "123"
        },
        "created_at": {
            "S": "2023-09-13T09:14:58+0000"
        },
    }
}
```

> There was no error but results still not reflecting.

**Comment by GrahamCampbell** [comment]
This was fixed by https://github.com/async-aws/aws/pull/1565.
