### ISSUE TITLE
Next release of media-convert should be 1.0

### ISSUE THREAD

**Issue by stof** [async-aws/aws#1648]
A few months ago, we agreed on Slack that the next version of async-aws/media-convert should be 1.0 as my experience running it in production is that it is stable enough for that.

However, this seems to have been forgotten as the release has been done as 0.1.3.

From what I can see, I suspect that this is related to the new automated release tooling, which would only bump to 1.0 on a BC break (unless it understand that `0.1` to `0.2` also allows BC breaks which is the point of starting at 0.x, and would then _never_ go to 1.0).
What is the process to declare a new package as stable enough for 1.0 ? Or should we stop using 0.x entirely ?

**Comment by jderusse** [comment]
Let's start at version 1.0
IMHO the code generator is stable enough to skip the 0.x versions

see #1649
