### ISSUE TITLE
AsyncAws/sqs error on parsing GetQueueUrlResult response

### ISSUE THREAD

**Issue by jkhavichmo** [async-aws/aws#1720]
Hi,
I am using Symfony 7 with aws sdk(3.308.6) sqs queue. Im getting the below error on getting the queue url from the getQueueUrl response; 
```
worker-1                   | In Response.php line 353:
worker-1                   |                                                 
worker-1                   |   [AsyncAws\Core\Exception\UnparsableResponse]  
worker-1                   |   Could not parse response as array             
worker-1                   | 
worker-1                   | Exception trace:
worker-1                   |   at /app/vendor/async-aws/core/src/Response.php:353
worker-1                   |  AsyncAws\Core\Response->toArray() at /app/vendor/async-aws/sqs/src/Result/GetQueueUrlResult.php:31
worker-1                   |  AsyncAws\Sqs\Result\GetQueueUrlResult->populateResult() at /app/vendor/async-aws/core/src/Result.php:139
worker-1                   |  AsyncAws\Core\Result->initialize() at /app/vendor/async-aws/sqs/src/Result/GetQueueUrlResult.php:24
worker-1                   |  AsyncAws\Sqs\Result\GetQueueUrlResult->getQueueUrl() at /app/src/.....
```

This is the code snippet:

```
    $sqsClient = new SqsClient($clientConfiguration, null, null, $logger);

    try {
      $url = $sqsClient->getQueueUrl(['QueueName' =>  'my-queue']);
      $urlStr = $url->getQueueUrl();
    }catch (Exception $e) {
      $this->logger->error(sprintf(" error getting queue url; %s", $e->getMessage()));
    }
```
This is the response from the aws-sdk

`<GetQueueUrlResponse><GetQueueUrlResult><QueueUrl>http://host:port/000000000000/my-queue</QueueUrl></GetQueueUrlResult><ResponseMetadata><RequestId>SO4VIFD7XHT6ZB7WOGQ5A1UVXHWAQBQ6FORUN4B22NT8FA12X6A4</RequestId></ResponseMetadata></GetQueueUrlResponse>`

The code had failed because the aws-sdk always returns xml as a response and async-aws/sqs on the other hand expects json;
The 'GET' method for json protocol is not mentioned in the aws doc: https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-making-api-requests-json.html; 

Switching to the async-aws/sqs ver 1.9.0 solved it.
Please let me know if you'd like me to copy this issue into the messenger project as well.
Thanks

**Comment by jderusse** [comment]
Hey, I failed to reproduce your issue

```
$client = new \AsyncAws\Sqs\SqsClient();

$url = $client->getQueueUrl(['QueueName' =>  'test']);
$urlStr = $url->getQueueUrl();
dump($urlStr);
```

just work.

Looking at you snippet `<GetQueueUrlResponse><GetQueueUrlResult><QueueUrl>http://host:port/000000000000/my-queue</QueueUrl>` I wonder if you are calling the AWS APIs, or you changed the endpoint to point to a mock service like `localstack` or `fake_sqs`

**Comment by jderusse** [comment]
Would you mind to give a tru to the latest (not tagged) version `@master`?

**Comment by jkhavichmo** [comment]
sure, what ver should I use  in my docker-compose file?

**Comment by jkhavichmo** [comment]
Thank you, everything works as expected
