### ISSUE TITLE
async-aws/sqs: Message deletion not working with ElasticMQ

### ISSUE THREAD

**Issue by akuma91** [async-aws/aws#1746]
Hey everyone

When I try to consume a message from ElasticMQ using Symfony messenger, I receive the following error upon trying to delete the message from the queue:

``` 
In Response.php line 432:
  HTTP 400 returned for "http://elasticmq:9324/".

  Code:    InvalidAction
  Message: Invalid request: UnacceptedResponseContentTypeRejection(Set(ContentType(none/none)))
  Type:
  Detail:
```

This seems to happen due to the `Accept` header `application/json` added in async-aws/sqs version 2.1.1 in the `src/Input/DeleteMessageRequest.php`.
Downgrading to async-aws/sqs version 2.1.0 (or removing the Accept header manually) fixes the issue.

Is there anything that can be done about this?

Setup:
- PHP 8.3.9
- ElasticMQ version 1.6.5
- Symfony application using `symfony/messenger` v6.4.9 and `symfony/amazon-sqs-messenger` v6.4.9
- async-aws/core v1.22.0
- async-aws/sqs v2.1.1

**Comment by jderusse** [comment]
Looks like it's a bug in ElasticMQ (https://github.com/softwaremill/elasticmq/issues/1027).

Could you try to update your docker image?

**Comment by akuma91** [comment]
Thanks for the advice, that fixed it!
