### ISSUE TITLE
Start using changelogs

### ISSUE THREAD

**Issue by Nyholm** [async-aws/aws#193]
Should we do it the symfony way? Ie both changelog in root and individual packages?

Alternatively we can just put changlog on the packages.

**Comment by jderusse** [comment]
Why not, some people use it.

but only in sub packages IMHO.
And this can be automated by the generator

**Comment by Nyholm** [comment]
The official SDK has a really nice way to automate releases. 
https://github.com/aws/aws-sdk-php/blob/master/CONTRIBUTING.md#changelog-documents

But Im not sure that is needed right now, is it?
It is cool though =)

**Comment by Nyholm** [comment]
There are some example change logs, Ie core package. 

I'll close this issue. Feel free to open a new one if we want to do something cool and automated.
