### ISSUE TITLE
Use official SDK to build Objects

### ISSUE THREAD

**Issue by jderusse** [async-aws/aws#2]
The official SDK contains JSON file describing every method/request/response

ie. https://github.com/aws/aws-sdk-php/blob/efdbdde0968355917470a255c0d2e509c49f7476/src/data/sqs/2012-11-05/api-2.json#L214-L229

To provide a library compatible with official Documentation, I suggest to use those files to generates our DTO/Objects.

The content of `simple-aws` is:
- low level logic to perform request, deal with response, authentication, pagination
- a developper tool to generate the Request/Response Functions based on SDK JSON files (similar to https://github.com/thecodingmachine/safe)

Optionnaly it will also provides:
- helper classes that provides a non-official but more friendly contract (`$s3->putFile($path)`) (ie like psr/cache vs psr/simple-cache)

What do you think?

**Comment by Nyholm** [comment]
Yeah, I think it make sense to use that to generate DTO objects. That is fine as long as the code is readable and does not look generated.

**Comment by jderusse** [comment]
an alternative could be to generate tests automatically, while maintaining code manually

**Comment by Nyholm** [comment]
We will see.. This is new to me.. 
Im currently trying to find a way to do something..

**Comment by Nyholm** [comment]
See #6

**Comment by Nyholm** [comment]
I think we can close this. 

Excellent idea btw. This took the project to a new level.
