### ISSUE TITLE
Implement all "incomplete tests"

### ISSUE THREAD

**Issue by Nyholm** [async-aws/aws#207]
There are test stubs that needs some love. Basically:
1. Add some `Input` data and verify the HTTP request
2. Add some HTTP response data and very `Result`

 - [x] CloudFormation
 - [x] S3
 - [x] Ses
 - [x] Sns
 - [x] Sts
 - [x] Sqs
 - [x] Lambda

<img width="600" alt="Screenshot 2020-02-23 at 18 55 50" src="https://user-images.githubusercontent.com/1275206/75117019-37c0e080-566e-11ea-9051-f199835c896f.png">

**Comment by jderusse** [comment]
there are no more "incomplete" tests.
