### ISSUE TITLE
[S3] Key prefixes

### ISSUE THREAD

**Issue by Nyholm** [async-aws/aws#225]
Should we treat these the same?

```
'Key' => 'foo.png',
```
```
'Key' => '/foo.png',
```

Currently we expect no leading slash. The problem occurs when we copy objects: 
https://docs.aws.amazon.com/AmazonS3/latest/API/API_CopyObject.html#API_CopyObject_Examples

That assumes we do one with leading slash and one without: 

```php
        $input = new CopyObjectRequest([
            'Key' => 'my-second-image.jpg',
            'Bucket' => 'my-bucket',
            'CopySource' => '/bucket/my-image.jpg',
        ]);
```

**Comment by jderusse** [comment]
hmmm I'm not sure that this should be handled by AsyncAws. IMHO we must stay close to the AWS documentation.

**Comment by Nyholm** [comment]
Okey. That is fair and a good rule of thumb. 

We let the AWS server handle the issue if you add an extra slash on `Key` or forget to add one on `CopySource`.
