### ISSUE TITLE
[Automatic PR] What if PR is not merged

### ISSUE THREAD

**Issue by Nyholm** [async-aws/aws#272]
What if: 

Day 0: Update in official SDK
Day 1: Bot creates a PR with updates
Day 2: We still dont merge that PR
Day 3: Update in official SDK
Day 4: ??

Will the PR be updated?
Will a new PR be created?

What if we merge the PR but not delete the branch?

**Comment by jderusse** [comment]
Bot push always in the same branch. So the PR should be updated.

Let's see what happens in the next days:
- [ ] If a PR is not merged, Does the BOT create a new PR?
- [ ] If a PR is not merged and new files are changed, Does the BOT update the PR with new commits?
- [ ] If a PR is close, Does the BOT reopen the PR?
- [ ] If a PR is close and new files are changed, Does the BOT reopen the PR?

**Comment by jderusse** [comment]
Bot created #273 while because of release of `3.133.29`, while we closed #269 (for release `3.133.28`)
That checks: `If a PR is close and new files are changed, Does the BOT reopen the PR?`

**Comment by jderusse** [comment]
Bot didn't reopened the PR meaning, we can check `If a PR is close, Does the BOT reopen the PR?`

**Comment by jderusse** [comment]
We can check the 2 remaining checkbox. And close the issue.
The bot force push to new commits with changes. Keep the PR up to date and don't creates new PR.

I don't know why github say's I'm the owner of the commit

**Comment by Nyholm** [comment]
Okey. Cool 
I thought it was you that modified the PR =)

**Comment by jderusse** [comment]
Probably because I added the SSH key used by the BOT to push code.
