### ISSUE TITLE
Configuration Fallback misbehaving

### ISSUE THREAD

**Issue by swiffer** [async-aws/aws#280]
I have a Bref based lambda function processing files stored in an s3 bucket on object creation events. Files are accessed via Flysystem v2.

Composer require:
```json
"bref/bref": "^0.5.16",
"async-aws/flysystem-s3": "^0.2.0",
```

When creating the S3Client I'm using these params:

```php
$client = new S3Client([
    'accessKeyId' => $config['username'],
    'accessKeySecret' => $config['password'],
    'region' => $config['region'],
]);
```

When trying to list files I'm getting this error

```
Code: InvalidToken
Message: The provided token is malformed or otherwise invalid.
```

From what I see in async-aws/core Configuration.php falls back to all env vars if an option is not specified. The Lambda has env vars for

AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY
AWS_SESSION_TOKEN

but I'm using a different user for accessing the s3 bucket when creating the client. I think when doing so the Configuration should not use the sessionToken from env vars.

**Comment by swiffer** [comment]
maybe we can replace `if (isset($options[$option])) {` with `if (array_key_exists($option, $options)) {` and
```php
$client = new S3Client([
    'accessKeyId' => $config['username'],
    'accessKeySecret' => $config['password'],
    'region' => $config['region'],
    'sessionToken' => null,
]);
```

**Comment by Nyholm** [comment]
Oh. That is interesting. Thank you for this issue. 

@swiffer, could you check the patch in #281?

**Comment by swiffer** [comment]
Hi @Nyholm - looks good. But how can I test this? Tried pointing composer to the the fix-env-session branch of jderusse/aws but that's the complete package and not the aws-core one

**Comment by Nyholm** [comment]
The easiest way is just to copy the full `Configuration.php` into your vendors folder. 
It is easy because this patch is only modifying one file. 

Im not sure there is another good way at the moment. Hm.. I'll create an issue for this

**Comment by swiffer** [comment]
@Nyholm - tested successfully.

Placed a copy of configuration.php in my src folder and excluded the vendor file via composer.json

```json
    "autoload": {
        "psr-4": {
            "App\\": "src/",
            "AsyncAws\\": "src/AsyncAws/"
        },
        "exclude-from-classmap": [
            "vendor/async-aws/core/src/Configuration.php"
        ]
    },
```

**Comment by jderusse** [comment]
thanks

**Comment by Nyholm** [comment]
Wohoo. Thank you
