### ISSUE TITLE
How to test PRs?

### ISSUE THREAD

**Issue by Nyholm** [async-aws/aws#285]
If someone submit a PR with a patch for a bug, how can that be tested before the PR is merged?

**Comment by Nyholm** [comment]
Maybe we should have a bot that deploy PRs into this organization: https://github.com/Async-AWS-PR

Then the bot writes a small message saying: "Hey, if you want to test this PR, write the following in composer.json". 

The bot has to be aware of our subtree split config. Maybe it is a good idea to use https://github.com/jderusse/docker-gitsplit

**Comment by jderusse** [comment]
does it worth it? People can copy/paste patches in their vendors

**Comment by Nyholm** [comment]
Sure, this is a "nice to have" feature. But I do think it makes sense when you are doing a multi repo setup like we are. 

(and, it is pretty cool)

**Comment by stof** [comment]
Another idea is to provide a `link` script as done in Symfony.
