### ISSUE TITLE
Remove AbstractApi::request()

### ISSUE THREAD

**Issue by Nyholm** [async-aws/aws#288]
This function is only used if you want to request an endpoint not implemented. Is this needed? 

On the other hand... it is only 2 lines of code..

**Comment by jderusse** [comment]
I'm wondering the exact same thing. I think we can remove it. (and flag it `@internal`)

**Comment by Nyholm** [comment]
`getResponse` is protected. So no need for the "internal", right?

**Comment by jderusse** [comment]
oh yes.. indeed
