### ISSUE TITLE
AWS DynamoDB support

### ISSUE THREAD

**Issue by GromNaN** [async-aws/aws#302]
Like S3, DynamoDB is one of the core services of AWS. It's a serverless document database. It would be great to have it in this library.

Documentation: https://docs.aws.amazon.com/aws-sdk-php/v2/guide/service-dynamodb.html

There is a few methods to implement:

- [ ] BatchGetItem
- [ ] BatchWriteItem
- [x] CreateTable
- [x] DeleteItem
- [x] DeleteTable
- [x] DescribeTable
- [x] GetItem
- [x] ListTables
- [x] PutItem
- [x] Query
- [x] Scan
- [x] UpdateItem
- [x] UpdateTable

Generic use-cases:
* Session handler https://docs.aws.amazon.com/aws-sdk-php/v2/guide/feature-dynamodb-session-handler.html
* Distributed lock https://aws.amazon.com/blogs/database/building-distributed-locks-with-the-dynamodb-lock-client/
* Sémaphore https://boylesoftware.com/blog/convenient-semaphore-dynamodb/
* Others https://docs.aws.amazon.com/aws-sdk-php/v2/guide/service-dynamodb.html

**Comment by Nyholm** [comment]
I agree!

Do you mind creating a PR?
Have a look here for how to generate these classes: https://github.com/async-aws/aws/blob/master/docs/maintainer-notes.md#creating-a-new-client-operation

**Comment by Nyholm** [comment]
Most of DynamoDb is implemented. The batch methods require some more work on the CodeGenerator. 

Im going to leave this for a while, but Im happy to review PRs.

**Comment by GromNaN** [comment]
I've tried to translate the [official documentation of `aws-php-sdk` ](https://docs.aws.amazon.com/aws-sdk-php/v2/guide/service-dynamodb.html)with your implementation.

State of operations testing:

- [ ] BatchGetItem
- [ ] BatchWriteItem
- [x] CreateTable
- [ ] DeleteItem
- [x] DeleteTable
- [x] DescribeTable
- [ ] GetItem
- [x] ListTables
- [x] PutItem
- [ ] Query
- [ ] Scan
- [ ] UpdateItem
- [ ] UpdateTable


The current result is here: https://gist.github.com/GromNaN/1e7a651871fd1ac174d02254bf9b3fe3

- I'm missing the `waitUntil` function for [`Waiters`](https://docs.aws.amazon.com/aws-sdk-php/v2/guide/feature-waiters.html?highlight=waiters), this is useful for the S3 client too.
- I get an error 400 when I try to get an item, without any error message.

**Comment by jderusse** [comment]
Thanks for your tests.
I've opened #332 to provides `TableExists` waiter.
```php
$client->tableExists(['TableName' => 'errors'])->wait();
```

`AttributeValue::$N` (and AWS) expect to be string, you should use `'time'    => array('N' => $time),`
I know the error could have been Improved => #333

later, use `echo $result->getItem()['id']->getN() . "\n";` instead of `['id']['N']`

**Comment by GromNaN** [comment]
Thank you for the review. 
I've update the [gist](https://gist.github.com/GromNaN/1e7a651871fd1ac174d02254bf9b3fe3). Everything works, including #333.
I've also added a waiter for delete table #338.

**Comment by Nyholm** [comment]
Everything? Ie all but two https://github.com/async-aws/aws/issues/302#issuecomment-600913215?

**Comment by jderusse** [comment]
Hat's the status of this issue? Shall we release Batch methods? Do we have a use-case?

**Comment by GromNaN** [comment]
We can release as this, the main features are implemented.

**Comment by Nyholm** [comment]
I tagged 0.1.0 of async-aws/dynamo-db

**Comment by jderusse** [comment]
Closing this issue. Let open a new one if we have a specific use-case for remaining operations
