### ISSUE TITLE
Add support for uploading big files on S3

### ISSUE THREAD

**Issue by stof** [async-aws/aws#337]
`PutObject` is limited to 5GB. Bigger objects (up to 5TB) require using a multipart upload. The official SDK has a `upload()` method, which handles this transparently (by default, it will switch to multipart much earlier than the 5GB threshold, probably because they found it more efficient or more reliable to upload in chunks). Does it make sense to provide the same kind of feature in this SDK ?

**Comment by jderusse** [comment]
probably because they don't implement signature on chunk/stream, and put the entiere payload in memory to generate the signature.

For now, we just provide a low level methods and let user deal with such edge cases.

But since the beginning we planned to add extra high level method/helper. I think this is a great candidate to start. Thank for the proposal.
We just have to figure out where to put that code.

**Comment by stof** [comment]
No, the 5GB limit is part of the PutObject endpoint itself. It is not about the signing part. It is about the fact that bigger files must be uploaded in several requests (I totally understand that they don't want to allow incoming requests with a 5TB body).

**Comment by jderusse** [comment]
I was talking about this `by default, it will switch to multipart much earlier than the 5GB threshold`.

**Comment by jderusse** [comment]
Thinking about that, I'm not sure it should be part of this project, It's more something that should be  managed by a high level application "flysystem-adapter" for instance.

One may want a `$ses->send('<html>')` that convert HTML to text. Or `$sqs->consume()` that handle all the complexity of polling the endpoint.
IMHO: Those thing should be managed by tools like "symfony/mailer-adapter" or "symfony/messenger-adapter"

**Comment by stof** [comment]
uploading a big file to S3 while taking into account the limitation of the S3 PutObject API (needing to switch to multipart upload) seems like a fit for a S3 SDK. That's only dealing with S3 APIs.
And this SDK does not even expose the multipart endpoints so a separate package cannot even do it (it would have to use the huge official SDK, and then it has nothing to do as the official SDK has the feature built-in).

**Comment by Nyholm** [comment]
I think this is an interesting feature. I think we should add it when there is users asking for it. As I understand from @stof, you are just making an observation of a missing feature, right?

The question we should ask us now is: Do we see that we can add this feature without breaking BC in the future?

**Comment by stof** [comment]
Well, the issues I opened for big files and presigned requests correspond to what I found missing to be able to migrate the Incenteev project from the official AWS SDK to `async-aws/s3` (based on a code review, not based on actually doing the migration, so I might have missed something).

**Comment by Nyholm** [comment]
I added a PR for this. See #403

**Comment by jderusse** [comment]
I think the point of @stof is providing a helper method `upload` that automatically switch from `putObject` to multipart upload if size of the file is too big. and take care of spliting the file in small part, and uploading them (re-uploading in case o retry).

**Comment by Nyholm** [comment]
Yes. 
I've been thinking on this. 

Could we (manually) create a simple abstraction layer of upload/download above the S3 client. Similar to the official SDK. 

```php
$s3 = new S3Client();
$simpleS3 = new SimpleS3Client($s3, 'example-bucket');

$simpleS3->upload($path, $file, $acl, $somethingElse);
$simpleS3->download($path);

```

**Comment by Nyholm** [comment]
Here is an example implementation: 

`object $data` is a value object we need to create for each method. 

```php
use AsyncAws\Core\Exception\Exception;
use AsyncAws\Core\Exception\Http\HttpException;
use AsyncAws\S3\Result\GetObjectOutput;
use AsyncAws\S3\S3Client;

class SimpleS3Client
{
    /**
     * @var S3Client
     */
    private $s3;

    /**
     * Default bucket if none is provided.
     *
     * @var string|null
     */
    private $bucket;

    public function __construct(S3Client $s3, ?string $bucket = null)
    {
        $this->s3 = $s3;
        $this->bucket = $bucket;
    }

    /**
     * @throws Exception
     */
    public function upload(object $data): bool
    {
        // TODO convert $data to $input

        if (!$input['Bucket']) {
            $input['Bucket'] = $this->bucket;
        }

        // TODO get content length from input or read body
        if ($contentLenth < 5 * 1024 * 1024 * 1024) {
            $this->s3->putObject($input);

            return true;
        }

        $uploadId = $this->s3->createMultipartUpload($input)->getUploadId();
        foreach ($data as $chunk) {
            $this->s3->uploadPart($input);
        }
        $this->s3->completeMultipartUpload($input);

        return true;
    }

    /**
     * @throws Exception
     */
    public function download(object $data): GetObjectOutput
    {
        // TODO convert $data to $input

        if (!$input['Bucket']) {
            $input['Bucket'] = $this->bucket;
        }

        // TODO convert input to GetObjectRequest

        $result = $this->s3->getObject($input);
        $result->resolve();

        return $result;
    }

    /**
     * @throws Exception
     */
    public function remove(object $data): bool
    {
        // TODO convert $data to $input

        if (!$input['Bucket']) {
            $input['Bucket'] = $this->bucket;
        }

        // TODO convert input to GetObjectRequest

        try {
            $this->s3->deleteObject($input);
        } catch (HttpException $e) {
            return false;
        }

        return true;
    }
}
```

**Comment by Nyholm** [comment]
If I can get some help with a draft of an API (or class skeleton) then I would be happy implementing this. 
I was sure it was a `SimpleS3` abstraction somewhere but I cannot find it.

**Comment by jderusse** [comment]
@Nyholm have a look to `https://github.com/aws/aws-sdk-php/blob/master/src/S3/ObjectUploader.php` for entrypoint  (which use https://github.com/aws/aws-sdk-php/blob/master/src/S3/MultipartUploader.php for handling multipart upload)

**Comment by Nyholm** [comment]
I started here: #653

@stof Could you have a look if the API is helpful for you?
