### ISSUE TITLE
[RFC] Use DateTimeImmutable everywhere instead of DateTimeInterface

### ISSUE THREAD

**Issue by stof** [async-aws/aws#363]
`DateTimeInterface` only contains the methods to format dates (`format`) and getters (`getTimestamp`, `getTimezone`, ...), as there are the only methods working exactly the same in `DateTime` and `DateTimeImmutable`. This makes the code a lot more complex when needing to manipulate dates (see the preSign logic for instance).
But allowing any DateTimeInterface has another drawback: the immutable value objects are not actually immutable. If I instantiate one of them and I provide a DateTime object, I can then actually mutate the date in this object.

I propose the following change:

- use `DateTimeImmutable` as type for all properties and return values in the library
- maybe keep accepting `DateTime` as input in constructors (either as a deprecated BC layer, or as a supported API), but convert the value to `DateTimeImmutable` (as done for string values)
- change argument types in internal APIs to use `DateTimeImmutable` (for the SignerV4 private APIs, I think that could actually already be done today, as it performs some conversion in public entrypoints anyway

What do you think @jderusse @Nyholm ?

**Comment by stof** [comment]
This is basically a revert of #94 but there is no justification about why this change was done.

**Comment by jderusse** [comment]
:+1: 

moreover it's a pain in the signer to jungle between DateTimeInterface and DateTimeImmutable as you mentioned it about presign

**Comment by Nyholm** [comment]
I’m fine with this. 
I converted everything to DateTimeInterface to comply with dependency inversion principle. I didn’t give it more thought than that. 

👍

**Comment by stof** [comment]
Well, DateTimeImmutable is a value object. There is no DI involved here AFAICT.

**Comment by Nyholm** [comment]
I provided a fix in #365
