### ISSUE TITLE
Handle ETag

### ISSUE THREAD

**Issue by Nyholm** [async-aws/aws#404]
In most API documentation the ETag is within quotes. ([ref](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListParts.html#API_ListParts_Examples))

```xml
<Part>
    <PartNumber>2</PartNumber>
    <LastModified>2010-11-10T20:48:34.000Z</LastModified>
    <ETag>"7778aef83f66abc1fa1e8477f296d394"</ETag>
    <Size>10485760</Size>
</Part>
```

If I call `$result->getETag()` I expect a string but no quotes. How should this be handled? 
Im not sure this is a real problem, it may be an issue with the docs...

Tests are failing in #403  because of this issue.

**Comment by jderusse** [comment]
This is not error, it's part of the RFC: an ETag have to be wrapped by quotes.

https://tools.ietf.org/html/rfc2616#section-14.19
https://tools.ietf.org/html/rfc2616#section-3.11
```
ETag = "ETag" ":" entity-tag

entity-tag = [ weak ] opaque-tag
weak       = "W/"
opaque-tag = quoted-string
quoted-string  = ( <"> *(qdtext | quoted-pair ) <"> )
qdtext         = <any TEXT except <">>
```

**Comment by Nyholm** [comment]
I did not know. Thank you.

The official SDK does not handle it in any special way and neither should we.
