### ISSUE TITLE
The website URL should be in the right place in the repo metadata

### ISSUE THREAD

**Issue by stof** [async-aws/aws#421]
Looking at https://github.com/async-aws/aws, the website is not clickable in the repo description. The URL seems to be in the description field rather than in the website field.

**Comment by stof** [comment]
Also, the website URL should also be added as the website of the organization.

**Comment by Nyholm** [comment]
Thank you. 
I added it on the organization. 

The repo overview is weird... I think Github recently changed it.. 
I've added things correctly: 


<img width="1272" alt="Screenshot 2020-03-31 at 19 40 46" src="https://user-images.githubusercontent.com/1275206/78057890-be609000-7387-11ea-814d-f579c98ca671.png">

¯\\_(ツ)_/¯

**Comment by jderusse** [comment]
it works now.. did you changed something?

**Comment by Nyholm** [comment]
I clicked "edit" and then "Save". No changes..

**Comment by jderusse** [comment]
thanks for reporting
