### ISSUE TITLE
Add a link to Github in the Website

### ISSUE THREAD

**Issue by jderusse** [async-aws/aws#431]
Sometimes, I'm looking for project in github, but google send me in doc.  I like when the link to github is accesible

**Comment by Nyholm** [comment]
There is a link in the sidebar. The very last item. Do you want another link?

**Comment by jderusse** [comment]
I was thinking about something with the logo and the word "github".
ie: https://api-platform.com/, https://mercure.rocks/, https://kubernetes.io/, https://docs.docker.com/engine/reference/commandline/build/
