### ISSUE TITLE
[Documentation] Update Pagination example

### ISSUE THREAD

**Issue by Nyholm** [async-aws/aws#432]
`S3Client::listObjectsV2` is a bit special since it returns two types of objects. We can make this example simpler by using a more normal result class.

**Comment by jderusse** [comment]
list of current paginated operations:

sqs::ListQueues

s3::ListMultipartUploads
s3::ListObjectsV2
s3::ListParts

lambda::ListLayerVersions

dynamodb::ListTables
dynamodb::Scan
dynamodb::Query

cloudformation::DescribeStacks
cloudformation::DescribeStackEvents
