### ISSUE TITLE
Add support for Cognito

### ISSUE THREAD

**Issue by shouze** [async-aws/aws#508]
We need the folloging operation at the moment:
- adminGetUser
- adminUpdateUserAttributes

**Comment by jderusse** [comment]
Up for a PR? https://async-aws.com/contribute/generate.html#creating-a-new-client

**Comment by shouze** [comment]
@jderusse I've made the PR. I don't know what's expected in terms of (unit) testing so far.

Also, I still don't have tried this new client in our app instead of the official aws sdk one at the moment.

**Comment by shouze** [comment]
I guess I also need to add some documentation :angel:?

**Comment by jderusse** [comment]
Yes, and probably few operations :wink:

Tests are automatically generated and will trigger a faillure.
You mostly have to copy/paste example provided by [Official Documenation](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_GetUser.html)

For the documentation, you don't have to describe all operations, just one or two example, how to use the client with concrete example.

**Comment by shouze** [comment]
Ok thanks, will do documentation tomorrow. I just don't know how to fix phpstan/flysystem errors at the moment. I'm pretty sure they are recent ones, related to the fact that action uses master phpstan action no?

Because same thing for https://github.com/async-aws/aws/pull/528

**Comment by starred-gijs** [comment]
Im also interested in this client (I actually began to generate the client before realising there is already a PR). These are the methods I need:

```
"AdminCreateUser",
"AdminDeleteUser",
"AssociateSoftwareToken",
"ChangePassword",
"ListUsers",
"SetUserMFAPreference",
"VerifySoftwareToken"
```

How can I contribute? Should I wait till you are done @shouze ?

**Comment by shouze** [comment]
> Im also interested in this client (I actually began to generate the client before realising there is already a PR). These are the methods I need:
> 
> 
> 
> ```
> 
> "AdminCreateUser",
> 
> "AdminDeleteUser",
> 
> "AssociateSoftwareToken",
> 
> "ChangePassword",
> 
> "ListUsers",
> 
> "SetUserMFAPreference",
> 
> "VerifySoftwareToken"
> 
> ```
> 
> 
> 
> How can I contribute? Should I wait till you are done @shouze ?

Yes you will get every method I’m almost done. You can probably expect something merged this week.

**Comment by jderusse** [comment]
> Yes you will get every method

No please, don't include the 99 methods exposed by AWS. Include the one you and @starred-gijs mentioned. And let people open an issue/PR with a use-case to include new methods.

**Comment by shouze** [comment]
@starred-gijs my PR is under review process I've generated all operations I need plus all you need :wink:

**Comment by shouze** [comment]
@starred-gijs is everything good for you? I confirm that I've replaced official aws sdk by aws async this morning and everything works as expected on my side :heart:.

**Comment by Nyholm** [comment]
Awesome!

**Comment by shouze** [comment]
@Nyholm just one thing: is it possible to release a new tagged version of the Symfony bundle? As from now I have to declare services. :angel: :pray:

**Comment by Nyholm** [comment]
Of course, Could you make a PR with changelog for 0.2.4?

**Comment by starred-gijs** [comment]
> @starred-gijs is everything good for you?

I tried it yesterday, and came to the point where I realised the bundle needed an updated, and then I got distracted with the SqsClient :) I plan to test it next week, will let you know my results!

**Comment by shouze** [comment]
> Of course, Could you make a PR with changelog for 0.2.4?

Here it is! https://github.com/async-aws/aws/pull/563

**Comment by Nyholm** [comment]
I tagged a new version of the symfony bundle: https://github.com/async-aws/symfony-bundle/releases/tag/0.2.4


Thank you
