### ISSUE TITLE
[WIP] Add ECS Credential Provider

### ISSUE THREAD

**Issue by nickaguilarh** [async-aws/aws#531]
Hey there, 
I'm using bref to deploy a server to lambda, everything works great but when I deploy to Codebuild using a custom ECS image it breaks since bref uses this package and this package doesnt support ECS Credentials.

~~Actually, bref package, uses async-aws/core, I don't know if is okey to submit the pr here or i should do in async-aws/core.~~

I will make a PR that adds support for this, hope that pr gets merged.

See: https://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.Credentials.EcsCredentialProvider.html

Greetings

**Comment by Nyholm** [comment]
Thank you for this issue. This will be a great addition.
