### ISSUE TITLE
[Core] OPTION_METADATA_SERVICE_TIMEOUT is expected to be float

### ISSUE THREAD

**Issue by Nyholm** [async-aws/aws#546]
From @nickaguilarh in https://github.com/async-aws/aws/pull/532#issuecomment-624848395

> Hey there
Today I was replacing the temporary fix made on our servers and I got a bug intruced on this PR,
On line 119 in Configuration.php it defines a ?string return value but the timeout is a float as specified on HttpClientInterface.php line 55.
How should we addres this?
Changing the timeout constant to string works just fine when env variable is not set, but I'm not sure if it will work in every case.
>
>I just realized this since we can't complete emulate AWS ECS Instances on local machine.

**Comment by nickaguilarh** [comment]
The comment I was doing on the PR: 
I don't think users will change timeout but taking into account what @jderusse said [here](https://github.com/async-aws/aws/pull/532#discussion_r420453890) there would be cases like [this](https://github.com/aws/aws-sdk-go/issues/1861) when will be needed to change that value, but that should be like 1% or less. 
So i guess it should be okey going back to use an argument on constructor, and on next major release allow Configuration class to return other type than string or null.
What do you say?

**Comment by jderusse** [comment]
:+1:  for removing this option and use a default 1.0 timeout.

what is the value of this enc variable on ECS serveur?

**Comment by nickaguilarh** [comment]
I'll write the pr to fix this setting timeout on constructor. 
By default it should be 1 second (1) but on certain cases like runing on and custom image on codebuild its value is empty. That's when it falls to default(which is float) and breaks.
