### ISSUE TITLE
Plan to support Laravel?

### ISSUE THREAD

**Issue by viezel** [async-aws/aws#547]
Supporting Laravel would be very beneficial. Bref and Vapor (serverless) would be great use cases for lowering the memory footprint.  As Laravel has a driver based approach, it could be a separate composer package that exposes the async-aws based drivers. 

I had a look at the Framework, and these were the places I found relevant

**SQS:**

- Connector: https://github.com/laravel/framework/blob/master/src/Illuminate/Queue/Connectors/SqsConnector.php
- Job: https://github.com/laravel/framework/blob/master/src/Illuminate/Queue/Jobs/SqsJob.php
- Queue: https://github.com/laravel/framework/blob/master/src/Illuminate/Queue/SqsQueue.php

**SES:**

- https://github.com/laravel/framework/blob/master/src/Illuminate/Mail/Transport/SesTransport.php

**Dynamo:**

- https://github.com/laravel/framework/blob/master/src/Illuminate/Cache/DynamoDbStore.php

**S3:**

So Laravel supports Flysystem out of the box, we only need a `asyncs3` driver

- https://github.com/laravel/framework/blob/master/src/Illuminate/Filesystem/FilesystemManager.php#L203-L213

**Comment by Nyholm** [comment]
Thank you for this issue. 

Of course, we should fix this. I added implementation for SQS here: https://github.com/laravel/vapor-core/pull/44

I think it make sense do build integrations for Laravel. Or maybe even Laravel will accept PRs to respective library.

**Comment by Nyholm** [comment]
I've added a few PRs. The SQS one is ready to merge after I added some tests. The other ones still needs some work. 

@viezel, It is highly appreciated if you want to help coding or testing

**Comment by viezel** [comment]
@Nyholm ill gladly help out. How feature rich is S3, SQS? 
I could test out the PR on some our projects that uses temp credentials, signed url and other more advanced features if S3.

**Comment by Nyholm** [comment]
> How feature rich is your version of S3, SQS?

It contains all we need. If we need anything else, then we just generate the missing operations. https://async-aws.com/contribute/generate.html

We are always happy to add more. But we should only add things we need.

**Comment by Nyholm** [comment]
So here is the progress: 

### Queue

I've added https://github.com/async-aws/illuminate-queue. It needs unit tests and tests. After that I'll tag 0.1.0. 

### Mail

PR is ready: https://github.com/async-aws/aws/pull/550. It is waiting to be merged. It is also missing tests. 

### Filesystem

PR is ready: https://github.com/async-aws/aws/pull/552. It is waiting to be merged. 
I think it is correct. Please verify if it works as expected. 

It is also missing tests. 

### Cache

The PR is not complete. It is in draft: https://github.com/async-aws/aws/issues/566
Im blocked by https://github.com/async-aws/aws/issues/566

**Comment by viezel** [comment]
Super quick response Tobias. Such a joy!

**Comment by Nyholm** [comment]
I’ve created 3 packages. I need help testing them and correcting bugs. 

It would be additionally super awesome if I got help adding unit tests.

**Comment by viezel** [comment]
Sure thing. I got a herniated (serious back pains) after lifting my 2yrs this morning. So hopefully I can stand up on Monday and help you out.

**Comment by Nyholm** [comment]
Oh, Im sorry to hear that. I hope you feel better soon. 

No rush. There is always plenty of things to do if you want to help. I can write unit tests but I am really in the dark when it comes to "write documentation how to use it in a Laravel app".

**Comment by viezel** [comment]
Thanks 😊 
I’ll help out.

**Comment by viezel** [comment]
Just looked at the filesystem package. It’s missing a ServiceProvider. This is what Laravel uses to register a new driver to the container. 

See here: https://github.com/academe/laravel-azure-file-storage-driver/blob/master/src/ServiceProvider.php

**Comment by viezel** [comment]
Same for queue. We need to register it. 
A guide: https://joedixon.co.uk/creating-a-custom-queue-driver-for-laravel

So we need a ServiceProvider for the queue 

```
$manager = $this->app['queue'];

$manager->addConnector('your-custom-driver-name', function()
{
    return new YourCustomConnector;
}); 
```

**Comment by Nyholm** [comment]
Thank you for the links and comments. I’ll add something after dinner.

**Comment by Nyholm** [comment]
I started some work here: https://github.com/async-aws/aws/pull/572

**Comment by viezel** [comment]
### How to test

1. checkout repo: [async-test](https://github.com/viezel/async-aws-laravel/tree/async-test)
2. `composer install`
3. edit `.env` with: your AWS credentials, SES email, redis endpoint, SQS queue name and account id on sqs prefix
4. run `php artisan serve`
5. open `routes/web.php` to see the test routes:

- http://127.0.0.1:8000/file-upload
- http://127.0.0.1:8000/file-exists
- http://127.0.0.1:8000/queue
- http://127.0.0.1:8000/mail
- http://127.0.0.1:8000/mail
- http://127.0.0.1:8000/cache-add
- http://127.0.0.1:8000/cache-check
- http://127.0.0.1:8000/cache-delete

**Comment by viezel** [comment]
@Nyholm I went into the test repo and added your [ServiceProviders manually](https://github.com/viezel/async-aws-laravel/commit/d94894659ba544b4c3f0023f1651bbbbdd89d722). 

we get the following results as a drop-in replacement:

- using s3: RuntimeException: Could not use AsyncAwsS3 since Flyststem v1 is not installed.
- using mail: Missing parameter "Destination" for "AsyncAws\Ses\Input\SendEmailRequest". The value cannot be null.
- using queue: just works 👍

**Comment by Nyholm** [comment]
Amazing!

Thank you for this. I tested all endpoints and fixed the bugs =)

**Comment by viezel** [comment]
@Nyholm I went through it all and it works. you can tag it now
