### ISSUE TITLE
DocBlock for list/map

### ISSUE THREAD

**Issue by jderusse** [async-aws/aws#554]
Currently Map and List are documented as `foo[]` (except for enums cases)

Shouldn't we use `list<foo>` and `array<string, foo>`?

**Comment by Nyholm** [comment]
Yeah, That is better. 
But would the CodeGenerator be way more complex if we did?

**Comment by jderusse** [comment]
nop, it should be ~ lines in TypeGenerator Class
I'll open a PR once #553 merged
