### ISSUE TITLE
Add documentation for Monolog

### ISSUE THREAD

**Issue by jderusse** [async-aws/aws#557]
related PR: #537

/cc @guillaumesmo

**Comment by guillaumesmo** [comment]
Which documentation is required?

What comes to my mind:
- at least document the constructor parameters
- prerequisites? (create log group, stream, IAM permissions)

I could provide an example usage for Symfony, is that out of the scope?

**Comment by Nyholm** [comment]
Sure, all 3 would be good to have<

**Comment by Nyholm** [comment]
Closed by #577
