### ISSUE TITLE
ssm parameter vault caching

### ISSUE THREAD

**Issue by Nemo64** [async-aws/aws#565]
I'm testing #490 and now that i'm using it I can say that the solution is better then I expected.

But I think that service needs caching since [pricing is in the cents per 1000 requests](https://aws.amazon.com/systems-manager/pricing/) compared to lambdas [cents per million requests](https://aws.amazon.com/lambda/pricing/) and the parameter loader will requests the parameters every time even if they are not needed.

A cache that stores these parameters in `cache.app` or a custom cache configuration should be fine. The idea of ssm parameters is to ease deployment and not to provide instant updates when changed. Although this should definitely be configurable.

I can try to implement something in the next time if there isn't an issue with my idea.

**Comment by jderusse** [comment]
Did you try runing `composer dump-env prod` to dump env config to a file.

Otherwise, I suggest to decorate either the SsmClient, or EnvLoader with local cache

**Comment by Nemo64** [comment]
Can I easily decorate the ssm client? I tried using a cached http client but since it is a post request: that does nothing. 
And dumping them into a file... well first of: the dumper isn't run in that case but wouldn't that be against the entire idea of having them in ssm?
I run a lambda environment and I can just use serverless to read those parameters during deployment wich isn't that beautiful since they are then in the cloudformation template and in the environment configuration of the lambda.
