### ISSUE TITLE
Support for custom Credential cache implementations

### ISSUE THREAD

**Issue by guillaumesmo** [async-aws/aws#585]
In the official AWS SDK for PHP, the default credentials chain (\Aws\Credentials\CredentialProvider::defaultProvider) accepts a \Aws\CacheInterface in the "credentials" config key. Also, the library provides implementations of PSR 6 and 16 for that interface (\Aws\PsrCacheAdapter, \Aws\Psr16CacheAdapter)

This is especially useful when using EC2 and ECS metadata credential providers, so the credentials can be stored in an APC cache for example instead of having a HTTP call on each request

I would like to work on such a feature for AsyncAWS
could you provide me some guidelines which I should follow if I want this merged eventually?

I see that \AsyncAws\Core\Credentials\CacheProvider already acts as a memory cache, maybe a good starting point

**Comment by jderusse** [comment]
Indeed CacheProcider is a good starting point.
I could accept an optional cache pool, and AsyncBundle could provide the glue to inject the cache.system

**Comment by Nyholm** [comment]
That is a good idea :+1:
