### ISSUE TITLE
Tag Laravel packages

### ISSUE THREAD

**Issue by Nyholm** [async-aws/aws#590]
I want to tag the Laravel packages. They are unit tested and semi documented. 

When someone test these in a real app and confirm that it is working as expected, then I’m happy to tag 0.1.0.

**Comment by viezel** [comment]
I just did a test on a real world app, and it seems the SQS integration has an issue. I don't process any queue jobs.
if I run `php artisan queue:work` which is Laravel lingo for pull messages from SQS, nothing happens. I do not receive any messages even though they are available.

@nyholm you can test this out in my [test app](https://github.com/viezel/async-aws-laravel/tree/async-test) like this:

1. pull the latest
2. visit: http://127.0.0.1:8000/queue-raw
3. run `php artisan queue:work`

**Comment by Nyholm** [comment]
Thank you for testing. 
I saw this in the logs: 

> [2020-05-10 18:07:31] local.ERROR: Invalid parameter "AttributeName" for "AsyncAws\Sqs\Input\ReceiveMessageRequest". The value "ApproximateReceiveCount" is not a valid "QueueAttributeName". {"exception":"[object] 

This should be a workaround: https://github.com/async-aws/aws/pull/598

**Comment by viezel** [comment]
yep that works.

**Comment by Nyholm** [comment]
Thank you again. 

All packages are tagged.
