### ISSUE TITLE
Find a solution for steaming responses

### ISSUE THREAD

**Issue by Nyholm** [async-aws/aws#60]
Currently, the only way to stream a response is to:

```php
$result = ...;
$info = $result->getInfo();
foreach($httpClient->stream($info['response']) as $chunk) {
  // ...
}
```

Do we want to provide a better way?

**Comment by jderusse** [comment]
I think people won't have to stream the AWS raw Response and this solution is fine.

Except one case: to download a S3 object that could be huge.
But in that case,  api2.json give us an information `Body: {type: stream}`.
Maybe in that case, we can generate a special Object that provides
-getContentAsString (or provides __tostring)
-getChunks (or implement iterrator
-getStream

from user land
```
class Stream
$result = $s3->getObject();
echo $result->getExpiration();
foreach ($result->getBody() as $chunk) {...}
```
WDYT?

**Comment by Nyholm** [comment]
I agree. 

I wanted it noted, it is not top priority.
