### ISSUE TITLE
[Laravel/s3] Calling Storage::url() fails

### ISSUE THREAD

**Issue by hmazter** [async-aws/aws#603]
With the storage configured with `'driver' => 'async-aws-s3'`.
Calling this:
```php
$publicUrl = Storage::url($filename);
```

Which is documented here: https://laravel.com/docs/7.x/filesystem#file-urls
Fails with the following error:

```json
{
    "message": "This driver does not support retrieving URLs.",
    "exception": "RuntimeException",
    "file": "/application/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php",
    "line": 440,
    "trace": [
        {
            "file": "/application/app/Services/ProfileImageService.php",
            "line": 18,
            "function": "url",
            "class": "Illuminate\\Filesystem\\FilesystemAdapter",
            "type": "->"
        },
        ...
    ]
}
```

The Flystem-adapter used internally is `AsyncAws\Flysystem\S3\S3FilesystemV1`.

Laravel checks if the adapter has a method `getUrl` or is an instance of some specified adapters and calls special methods for those.
But since `S3FilesystemV1` does not have a `getUrl` or is listed in the special cases it will fail. Or am I missing something?
https://github.com/laravel/framework/blob/7.x/src/Illuminate/Filesystem/FilesystemAdapter.php#L421

**Comment by Nyholm** [comment]
I think you are correct. 

Reading [the code](https://github.com/illuminate/filesystem/blob/v7.10.3/FilesystemAdapter.php#L421-L443). Im not sure what object `$adapter` or `$this->driver` is. Could you help me debug that?

What do you think is the best solution? To implement a `getUrl()` on our own `FilesystemAdapter` or to extend that `S3FilesystemV1` in `async-aws/illuminate-cache` and implement `getUrl()` there?

Im not 100% sure to be honest. But probably the first one..

**Comment by Nyholm** [comment]
Could you have a look at #610?
