### ISSUE TITLE
The code generator should always use LF line endings

### ISSUE THREAD

**Issue by stof** [async-aws/aws#611]
Currently, the code generator uses `PHP_EOL`. This means that the generated code will be different if the dev running it is on Windows. This does not make sense IMO.

**Comment by jderusse** [comment]
:+1: my bad. 
I think all those `PHP_EOL` were added in #605. I pushed the commit https://github.com/async-aws/aws/pull/605/commits/0538970ccc2e1adeb681826ea9e0cfa5151c2c5e to  fix them.

Didn't not find any other occurence (except in the doc, but this is fine)

**Comment by Nyholm** [comment]
Thank you. 

This is fixed in #605
