### ISSUE TITLE
[S3] Use virtual hosted style urls 

### ISSUE THREAD

**Issue by Nyholm** [async-aws/aws#612]
This might have been fixed in #605. 

We are currently using "path-style request". For buckets created after 2020-09-30, this will not work. See https://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAPI.html

**Comment by stof** [comment]
I don't think #605 fixes it. It does nothing to inject the bucket name in the host.

**Comment by shyim** [comment]
I hope this will be configureable. It's easier for local development with minio :)

**Comment by stof** [comment]
Well, given that AWS plans to end support for path-style requests, does it need to be configurable ?

**Comment by shyim** [comment]
I don't know what the really focus here is. But there are many s3 compatible storages out from other providers. Some of it requires path-style requests
