### ISSUE TITLE
Presign URL warning about expiration

### ISSUE THREAD

**Issue by Nyholm** [async-aws/aws#619]
The URL might expire before the date we provided because the access token expires. 

Should we mention this in the docs?

See https://aws.amazon.com/premiumsupport/knowledge-center/presigned-url-s3-bucket-expiration/

**Comment by jderusse** [comment]
Given it's not a bug or special edge case introduced by AsyncAws library, I'm not sure we should mention it.

I want to avoid creating a Knowledge base for AWS. Let's see if we have too many opened bug about it.

**Comment by Nyholm** [comment]
I dont think we should be a knowledge base for AWS either. But we could afford to give a link to them in the section about presign. 

> Note the AWS limitations: [link]

**Comment by jderusse** [comment]
let's do it
