### ISSUE TITLE
[S3] S3Client::getUrl()

### ISSUE THREAD

**Issue by Nyholm** [async-aws/aws#620]
This was mentioned in #610. 

If you have a public bucket, you may want to have a link to the object. Should we add `S3Client::getUrl()` with an implementation like the one in #610?

Or should this be in a integration layer?

**Comment by jderusse** [comment]
related to #337 : should we add "helper" functions in the client.

I still think those methods should be part of a dedicated integration. Or at least an dedicated Class in S3 namespace, in order to let the Client as close as possible to the AWS SDK.

```php
$helper = S3Helper(new S3CLient());
$helper->upload($bucket, $filename, $options = []);

$helper->getUrl($bucket);
```

**Comment by Nyholm** [comment]
Or should we do something like this?

```php
class SimpleS3 extends S3Client {
  public function get(/*...*/) {}
  public function put(/*...*/) {}
  public function getUrl(/*...*/) {}
}
```

And put this in a separate package.
