### ISSUE TITLE
Should SimpleS3Client inherit S3Client or use composition?

### ISSUE THREAD

**Issue by Nyholm** [async-aws/aws#659]
The discussion started here https://github.com/async-aws/aws/pull/653#issuecomment-633710704. 

Reasons for inheritance: 

- It allows `SimpleS3Client::getUrl()` to use protected `S3Client::getEndpoint()`
- It will be easier for services that needs both a "simple" upload method and advanced stuff. 

Reasons for composition: 

- It is almost always the right thing to do.

**Comment by Nyholm** [comment]
I like the fact it is using inheritance. It will allow say the Flysystem adapter to do all the simple things like download and upload files larger than 5Gb. And it will aslo allow the Flysysten adapter to do complex things like `headObject`, copy files etc. And only have dependency on one client. 

I vote for keeping it as it is.

**Comment by jderusse** [comment]
Agreed. Let's keep this class as it is. And re-open the discussion when needed.
