### ISSUE TITLE
Cognito identity provider adminInitiateAuth function missing

### ISSUE THREAD

**Issue by Manuelacosta98** [async-aws/aws#663]
is there a pattern to follow to add a new function? 

I am willing to contribute this function but i am not familiar with OSS.

Thanks

**Comment by jderusse** [comment]
hello @Manuelacosta98 thank you for your help 
here is documentation about adding new operation: https://async-aws.com/contribute/generate.html

**Comment by Manuelacosta98** [comment]
i need to fork the repo to make the Draft PR ? @jderusse Thanks for the help

**Comment by jderusse** [comment]
hello, yes you need to first 
- fork this repository
- then clone your fork on your local environnement
- create a new branc
- add new operations
- commit and push to your fork
- create a PR on this PR

**Comment by Manuelacosta98** [comment]
![Screenshot from 2020-05-30 17-00-43](https://user-images.githubusercontent.com/33484814/83338964-33bce400-a297-11ea-84b2-f49aed8a9e1f.png)

I get this error when trying to generate adminInitiateAuth, i am using PHP 7.3.14

**Comment by jderusse** [comment]
Sometime some combination of shapes (internal representation of AWS SDK) are not implemented and need some adjustement in our AsyncAws generator.

I've fixed in to #664 and added the method `adminInitiateAuth`. Are you sur you need only this operation ?

**Comment by Manuelacosta98** [comment]
yes only that thanks i guess this is close then?
