### ISSUE TITLE
Release DynamoDB

### ISSUE THREAD

**Issue by tyx** [async-aws/aws#695]
Hello !

Any chance to have a new release of DynamoDB including my latest change about nullable array ?

Thanks !

**Comment by Nyholm** [comment]
Yes, of course. Thank you for creating the issue. 

I've reviewed the diff: https://github.com/async-aws/dynamo-db/compare/0.3.0...master
The BC break tests are green. 
I've also created a PR with the changelog: #696

**Comment by tyx** [comment]
Thank you !

**Comment by Nyholm** [comment]
Thank you for your work
