### ISSUE TITLE
Release RDS data service

### ISSUE THREAD

**Issue by Nyholm** [async-aws/aws#718]
Work started by @Nemo64. We simplified the [original PR](https://github.com/async-aws/aws/pull/645) and said that additional work should be completed in a second PR. 

What is the status of this?

@Nemo64 are you currently using this package?

**Comment by Nemo64** [comment]
Not at the moment. I have a branch the implemented it: https://github.com/Nemo64/dbal-rds-data/tree/feature/async-aws
And it seemed to work but I couldn't find time to test it in terms of performance and how the parameters work as the async-aws implementation sets many fields, that shouldn't be set, with null.

**Comment by Nyholm** [comment]
About the null issue: It might be fixed now after https://github.com/async-aws/aws/pull/668

**Comment by Nemo64** [comment]
Ok, i finally found time to test it (at least for functionality).

It works great. I can't speak for detailed performance yet but I could integrate it into an existing project without noticeable ill effects. Parameters, Transactions, Migrations etc. all work.

I don't use the BatchExecuteStatement api call in my library but i build an arbitrary test case just to check. It was the most complicated api call after all. But it works too.
```php
        $connection->getClient()->batchExecuteStatement([
            'resourceArn' => $connection->getResourceArn(),
            'secretArn' => $connection->getSecretArn(),
            'database' => $connection->getDatabase(),
            'sql' => 'INSERT INTO message SET `user` = :user, `body` = :body',
            'parameterSets' => [
                [
                    ['name' => 'user', 'value' => ['stringValue' => 'username']],
                    ['name' => 'body', 'value' => ['stringValue' => 'message body']],
                ],
                [
                    ['name' => 'user', 'value' => ['stringValue' => 'username2']],
                    ['name' => 'body', 'value' => ['stringValue' => 'message body2']],
                ],
            ]
        ]);
```

So in general, thumbs up from me 👍 .

**Comment by Nyholm** [comment]
Nice. 

Thank you for testing. I've release 0.1.0: https://github.com/async-aws/rds-data-service/releases/tag/0.1.0
