### ISSUE TITLE
S3 client unusable with Scaleway

### ISSUE THREAD

**Issue by chapa** [async-aws/aws#757]
Hi,

I would like to use the S3 client to connect to a Scaleway S3 bucket, but I get an `UnsupportedRegion` exception.

The region I have to use is `fr-par`, but it's not listed in the switch of the [`getEndpointMetadata`](https://github.com/async-aws/aws/blob/6cf3d03ec4dcb36a41d59adae6236015a7a9901c/src/Service/S3/src/S3Client.php#L735) method.
I tried to omit the region but then I get an error from the endpoint : `The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'fr-par'`

[Documentation](https://async-aws.com/clients/s3.html#non-aws-s3-endpoints) says that it is possible to use alternative endpoints, but either I'm missing something in the configuration or it is not possible.

In my case the `getEndpointMetadata()` is only called in [`getSigner()`](https://github.com/async-aws/aws/blob/6cf3d03ec4dcb36a41d59adae6236015a7a9901c/src/Core/src/AbstractApi.php#L224), maybe the call should be avoided when a custom endpoint is provided in configuration (like it's done in [`getEndpoint()`](https://github.com/async-aws/aws/blob/6cf3d03ec4dcb36a41d59adae6236015a7a9901c/src/Core/src/AbstractApi.php#L192)) ?
But then it may be necessary to provide `signService` and `signVersion` otherwise (via configuration ?)

**Comment by Nyholm** [comment]
Hey. 

Could you show a code example of what you are doing?

**Comment by chapa** [comment]
I don't actually use the objects like this (I'm using `league/flysystem-bundle` with `async-aws/flysystem-s3`), but this piece of code isaolates the problem :

```php
$client = new S3Client([
    'endpoint' => 'https://s3.fr-par.scw.cloud',
    'region' => 'fr-par',
    'accessKeyId' => '123',
    'accessKeySecret' => '123',
]);

$client->listObjectsV2([
    'Bucket' => 'my-bucket'
]);
```

Result :
```
PHP Fatal error:  Uncaught AsyncAws\Core\Exception\UnsupportedRegion: The region "fr-par" is not supported by "S3". in [...]/vendor/async-aws/s3/src/S3Client.php:826
Stack trace:
#0 [...]/vendor/async-aws/core/src/AbstractApi.php(229): AsyncAws\S3\S3Client->getEndpointMetadata()
#1 [...]/vendor/async-aws/core/src/AbstractApi.php(116): AsyncAws\Core\AbstractApi->getSigner()
#2 [...]/vendor/async-aws/s3/src/S3Client.php(469): AsyncAws\Core\AbstractApi->getResponse()
#3 [...]/index.php(15): AsyncAws\S3\S3Client->listObjectsV2()
#4 {main}
  thrown in [...]/vendor/async-aws/s3/src/S3Client.php on line 826
```

And if I remove the `'region'` :
```
PHP Fatal error:  Uncaught AsyncAws\Core\Exception\Http\ClientException: HTTP 400 returned for "https://s3.fr-par.scw.cloud/my-bucket?list-type=2".

Code:    AuthorizationHeaderMalformed
Message: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'fr-par'
Type:    
Detail:  
 in [...]/vendor/async-aws/core/src/Response.php:358
Stack trace:
#0 [...]/vendor/async-aws/core/src/Response.php(117): AsyncAws\Core\Response->getResolveStatus()
#1 [...]/vendor/async-aws/core/src/Response.php(81): AsyncAws\Core\Response->resolve()
#2 [...]/index.php(15): AsyncAws\Core\Response->__destruct()
#3 {main}
  thrown in [...]/vendor/async-aws/core/src/Response.php on line 358
```

**Comment by Nyholm** [comment]
Thank you. 

Does the problem still happens if you add `'pathStyleEndpoint' => true,` to the S3Client config?

**Comment by chapa** [comment]
Yes it does

**Comment by jderusse** [comment]
Hello @chapa could you please check the patch here https://github.com/async-aws/aws/pull/761/files ?

note: You probably have to enable `pathStyleEndpoint` because Scaleway probably does not handle calls to `https://my-bucket.s3.fr-par.scw.cloud`

**Comment by chapa** [comment]
Hi @jderusse sorry for the delay, it works perfectly with the patch

And btw it works with and without having `pathStyleEndpoint` enabled

**Comment by chapa** [comment]
Thank you ! :+1:
