### ISSUE TITLE
Use SimpleS3 client in Flysystem integration

### ISSUE THREAD

**Issue by Nyholm** [async-aws/aws#760]
This will allow flysystem to upload files larger than 5Gb. 

We could implement it as a soft requirement. Ie, if the S3Client is an instance if SimpleS3, then we use the `upload()` function over `putObject()`.

**Comment by Nyholm** [comment]
PR #772 will fix this for Flysystem 2. 

Because the return value of "upload" in Flysystem1 needs to have some metadata, ie path, etag and versionId, then I cannot implement this without breaking BC..

**Comment by Nyholm** [comment]
### Option A)
We could make SimpleS3 return an object with that metadata. But it will not make it simple anymore. 

The return type would be `SimpleS3::upload(/**/): CompleteMultipartUploadOutput | PutObjectOutput`. Im not sure I like that. 

### Option B)

We could make `S3FilesystemV1::upload()` only return "path" metdata. But that will be a worse experience for most user... 

I rather force the people that uploads massive files not to use an abstraction or to use Flysystem 2. 

### Option C)

We close this issue as it is fixed in #722. 

------------

I vote for C.

**Comment by jderusse** [comment]
I vote for C, people uploading big file AND using AsyncAws can switch to FlysystemV2
