### ISSUE TITLE
[S3] Presigned urls for upload and download 

### ISSUE THREAD

**Issue by Manuelacosta98** [async-aws/aws#790]
Hi good day, i am trying to find this function in the s3 repository with no success, for clarification this is what i am trying to achieve: https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/s3-presigned-url.html

`
//Creating a presigned URL
$cmd = $s3Client->getCommand('GetObject', [
    'Bucket' => 'my-bucket',
    'Key' => 'testKey'
]);

$request = $s3Client->createPresignedRequest($cmd, '+20 minutes');

// Get the actual presigned-url
$presignedUrl = (string)$request->getUri();
`

This is who is done in the aws/php-sdk, i cant find this function in the generate command, Thanks for the help would love to contribute.

**Comment by jderusse** [comment]
here is some documentation about presign url with async-aws https://async-aws.com/features/presign.html

**Comment by Manuelacosta98** [comment]
Thanks my bad. @jderusse

**Comment by jderusse** [comment]
You're welcome
