### ISSUE TITLE
Bug on overriding configuration in Symfony Integration

### ISSUE THREAD

**Issue by dcsg** [async-aws/aws#793]
Before I explain the bug I'm not sure if this is a bug on the Symfony Integration or from the Symfony itself.

What is hapenning:

I have the `config/async_aws.yaml` with the following:
![image](https://user-images.githubusercontent.com/744921/94576380-2cb9d880-026d-11eb-8d3b-6e12b6d45ba4.png)

I'm trying to override it for `dev` enviroment with the following in this file `config/dev/async_aws.yaml`:

![image](https://user-images.githubusercontent.com/744921/94576464-422f0280-026d-11eb-9e0d-1b689298f698.png)

This is the error I get:

![image](https://user-images.githubusercontent.com/744921/94577133-1d875a80-026e-11eb-8ece-01a41ebf4336.png)

I was able to debug it and I noticed that when processing the config files when merging it does not keep the names of the files it is overriding, here is a printscreen of it:

![image](https://user-images.githubusercontent.com/744921/94577417-7b1ba700-026e-11eb-91f4-00124d935693.png)

What I would expect is that the `sharedCredentialsFile` had the value that is in the `0` key of the `$currentConfig`.

Using:
- Symfony 4.4.13
- async-aws/async-aws-bundle:1.0.0
- async-aws/dynamo-db-session:0.1.1
- PHP 7.2

**Comment by Nyholm** [comment]
Thank you. 

I think we are doing something wrong.. I'll see if I can find it

**Comment by dcsg** [comment]
Also I noticed a bug that using dot folders the `is_readable` does not work properly and returns false but if I use `scandir` it shows the file is really weird. Are you aware of that?

**Comment by Nyholm** [comment]
No, Thank you for reporting that.

**Comment by jderusse** [comment]
> Also I noticed a bug that using dot folders the `is_readable` does not work properly and returns false but if I use `scandir` it shows the file is really weird. Are you aware of that?

Are you sure the user that run PHP, is able to read this file (permission settings)? `is_readable` is not just about checking if the file exist.

**Comment by dcsg** [comment]
> > Also I noticed a bug that using dot folders the `is_readable` does not work properly and returns false but if I use `scandir` it shows the file is really weird. Are you aware of that?
> 
> Are you sure the user that run PHP, is able to read this file (permission settings)? `is_readable` is not just about checking if the file exist.

yes, I did double check that. It was simple as copy the file from a dot folder to a "regular" folder and it worked and I even forced the permissions of the file to test if it was something wrong with that

**Comment by jderusse** [comment]
If the file exists and you have permission to read it, it's a bug that should be reported to PHP

**Comment by Nyholm** [comment]
I added a fix for the override config here: https://github.com/async-aws/aws/pull/795

**Comment by Nyholm** [comment]
@dcsg Did you confirm that it is a bug in PHP?

**Comment by dcsg** [comment]
> @dcsg Did you confirm that it is a bug in PHP?

I will double check but might also be an issue with `docker-sync` so don't bother at it I would say.
