### ISSUE TITLE
Requests with timeout are not retried. 

### ISSUE THREAD

**Issue by jderusse** [async-aws/aws#806]
Maybe this trace will help from Sentry. Im more than happy to track down if this is a bug or not. Contact me directly
![Screenshot 2020-10-09 at 11 36 20](https://user-images.githubusercontent.com/42832118/95568312-5967b000-0a24-11eb-9f33-6732c2ed1e58.png)

_Originally posted by @starred-gijs in https://github.com/async-aws/aws/issues/708#issuecomment-706083453_

**Comment by stof** [comment]
For reference, work is in progress at https://github.com/symfony/symfony/pull/38501
