### ISSUE TITLE
[S3] Disable transferring payload in multiple chunks

### ISSUE THREAD

**Issue by vlastv** [async-aws/aws#874]
Upload with multiple chunks realised in https://github.com/async-aws/aws/pull/226 not supported by S3-compatible services. For example, S3 middleware for Openstack Swift does [not support this](https://github.com/openstack/swift/blob/master/swift/common/middleware/s3api/s3request.py#L819).

We need a flag to switch to using chunks.

**Comment by Nyholm** [comment]
Hm. Sorry for asking, but are you referring to the code in `SignerV4ForS3`? Ie, when the file is larger that 64kB, then we split it to chunks?

I dont remember why we have that limit, @jderusse do you recall?

**Comment by jderusse** [comment]
I'm not sure changing the limit fixes the issue.
Chunk Body improve UX by avoiding reading the file twice (to compute hash) which could be an issue when file is really big (performance) or content is not a file (ie. streamed from another http client).

I've opened a PR to provide a flag to disabled this behavior (see #911)

I just wonder if the default should be enabled (current behavior) or disabled (I'm not sure it really worth it + AWS don't provides this)

**Comment by Nyholm** [comment]
Default should be enabled IMHO.
