### ISSUE TITLE
Pre-Signed POST

### ISSUE THREAD

**Issue by marliotto** [async-aws/aws#875]
Hello,
How to create presigned POST?
aws/aws-sdk-php has Aws\S3\PostObjectV4, but new API has no.

https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/s3-presigned-post.html
https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-UsingHTTPPOST.html

**Comment by jderusse** [comment]
Hey @marliotto ,

This repository is not related to the official AWS SDK. You should probably ask to https://github.com/aws/aws-sdk-php

Presigning URL with this Repository (async aws) is documented here https://async-aws.com/features/presign.html
