### ISSUE TITLE
Missing regions eu-west-2 / eu-west-3 in src/Service/Ses/src/SesClient.php

### ISSUE THREAD

**Issue by Asenar** [async-aws/aws#879]
Hi, 

async-aws/ses does not work for region eu-west-3, this case is missing in file `src/Service/Ses/src/SesClient.php`

I try to figure out how this code is generated to make a PR but I didn't find it …

**Comment by Nyholm** [comment]
Thank you for this issue. It will be fixed by #880

**Comment by Nyholm** [comment]
Could you check if dev-master works as you expect?

**Comment by Asenar** [comment]
It works, thanks !
