### ISSUE TITLE
type error after upgrading Symfony to 5.2.0

### ISSUE THREAD

**Issue by swiffer** [async-aws/aws#882]
Argument 3 passed to Symfony\Component\HttpClient\RetryableHttpClient::__construct() must be of the type int, null given, called in ../vendor/async-aws/core/src/AbstractApi.php on line 69

**Comment by yivi** [comment]
This has been fixed [in master](https://github.com/async-aws/core/blob/dfffde5dfbe5786eb13446047c538c5581e8c39b/src/AbstractApi.php#L71).

I imagine a new release is forthcoming.

**Comment by jderusse** [comment]
Indeed the code is fixed but not yet tagged. You can use `async-aws: dev-master` as a workaround. Or wait a new release (I'll do it today)

**Comment by jderusse** [comment]
Fixed by https://github.com/async-aws/core/releases/tag/1.7.0

**Comment by stayallive** [comment]
Thanks for the quick release 👍
