### ISSUE TITLE
`sendMessage` method not found when mocking `SqsClient`

### ISSUE THREAD

**Issue by aradoje** [async-aws/aws#89]
When trying to mock `SqsClient` from the official AWS SDK i get the following error:
```
Trying to configure method "sendMessage" which cannot be configured because it does not exist, has not been specified, is final, or is static
```
because the method does not belong class but is somehow added to it. Please keep this in mind when releasing the stable version and dont make the same structure as the official SDK.

**Comment by jderusse** [comment]
Our philosophy aims to reduce complexity of official SDK and emphasise the Developer eXperience.
By removing magic methods, redundante "async" methods and spaghetti middlewares...

Have a look to our SqsClient: https://github.com/async-aws/aws/blob/98a467b305418466d2f59df0ff96fdd7c3a11ba9/src/Sqs/SqsClient.php#L20-L48

Is it something that would address your issue?

**Comment by aradoje** [comment]
Yes, that is exactly what I need. I just wanted to state the issue I'm having to compliment the work and point the importance of not removing it :grin:

**Comment by Nyholm** [comment]
First version is released. And it is easy to mock.

**Comment by aradoje** [comment]
Awesome! Thanks.
