### ISSUE TITLE
Intermittent failure while loading token in EKS with service accounts

### ISSUE THREAD

**Issue by Jean85** [async-aws/aws#900]
I'm running a Symfony app in EKS, and I'm using SQS with Messenger + this lib.

I'm having small clusters of failures at long intervals with 403 responses from the SQS APIs:
```
HTTP 403 returned for "https://sqs.eu-central-1.amazonaws.com/".

Code:    AccessDenied
Message: Access to the resource https://sqs.eu-central-1.amazonaws.com/ is denied.
Type:    Sender
Detail:
```
I've dig into the logs, and I've found this warning:
```
php.WARNING: Warning: file_get_contents(/var/run/secrets/eks.amazonaws.com/serviceaccount/token): failed to open stream: No such file or directory {"exception":"[object] (ErrorException(code: 0): Warning: file_get_contents(/var/run/secrets/eks.amazonaws.com/serviceaccount/token): failed to open stream: No such file or directory at /var/www/my-project/vendor/async-aws/core/src/Credentials/WebIdentityProvider.php:92)"} []
```
So I've traced down the issue to something that happened on the official SDK too: https://github.com/aws/aws-sdk-php/issues/2014

Basically, it's a combination of:
 * tokens are short lived
 * EKS replaces tokens on-the-fly
 * PHP's realpath cache gets in the way...

... so you get brief intervals in which you try to read the old, now missing token.

In the offical SDK, the issue was mitigated by clearing the cache in a precise and ordered way of the following paths:
```
/var/run/secrets/eks.amazonaws.com/serviceaccount/..data/token
/var/run/secrets/eks.amazonaws.com/serviceaccount/..data
/var/run/secrets/eks.amazonaws.com/serviceaccount/token
```
in this PR: https://github.com/aws/aws-sdk-php/pull/2043

Can we apply the same logic here too?

**Comment by Jean85** [comment]
I've deployed the patch from #901 but today I got hit again by this same issue, it doesn't seem to work :(

**Comment by Nyholm** [comment]
What? Impossible :/

Do you have any idea why? Are you also using a cache in you Credentials chain?

**Comment by jderusse** [comment]
> What? Impossible :/
> 
> Do you have any idea why? Are you also using a cache in you Credentials chain?

Good catch about cache credential.
- 1. fetch file token
- 2. retrieve credentials from the token
- 3. reuse the same credentials even when they expires

This should not happens because credentials contains a "expiration date" and we use it. But we maybe have a bug.

Would be great if you can reproduce the bug and adds debugs:
- checks crendentials used when it works and when it fails
- checks the content of token when it works and when it fails

**Comment by Jean85** [comment]
I still got the same PHP warning (but on the new line, confirming that I'm using the patch):

```
php.WARNING: Warning: file_get_contents(/var/run/secrets/eks.amazonaws.com/serviceaccount/token): failed to open stream: No such file or directory {\"exception\":\"[object] (ErrorException(code: 0): Warning: file_get_contents(/var/run/secrets/eks.amazonaws.com/serviceaccount/token): failed to open stream: No such file or directory at /var/www/my-project/vendor/async-aws/core/src/Credentials/WebIdentityProvider.php:139)\"} []
```

My configuration is a default one with Symfony Messenger, using `sqs://sqs.eu-central-1.amazonaws.com` as DSN; credentials are present on the filesystem thanks to a service account bound to the EKS pod where the app is running. If no cache is provided by default, I'm not using any.

**Comment by Jean85** [comment]
From the PHP docs, first comment: https://www.php.net/manual/en/function.clearstatcache.php

> clearstatcache() does not canonicalize the path. clearstatcache(true, "/a/b/c") is different from clearstatcache(true, "/a/b//c").

I'm double-checking what we're doing, but it seems correct to me...

**Comment by Nyholm** [comment]
> If no cache is provided by default, I'm not using any.

It is by default if you are using the AsyncAws Bundle. You have to specifically opt-out of the caching. 

```yaml
async_aws:
    credential_provider_cache: null
```

**Comment by Nyholm** [comment]
(if you provided a value for `async_aws.credential_provider` then we will not add cache.

**Comment by Jean85** [comment]
@Nyholm nope, I'm not using that bundle, but `symfony/amazon-sqs-messenger`.

**Comment by Nyholm** [comment]
Looking at the AbtractApi's constructor, I see that we create a "default chain", and then wrap that around in a "in-memory cache". 

If you are using `symfony/amazon-sqs-messenger`, is it safe assume your working is running for multiple messages? Ie, it is up for a few minutes within the same request?

If so, it will never fetch the new config. You could confirm this idea by modifying the AbtractApi's constructor to not add the `CacheProvider` .

**Comment by Jean85** [comment]
@Nyholm I'm hitting the issue on a single controller that tries to dispatch a message, not while consuming, so that's not the issue.

DAMN! I've found the issue, the patch is a dud!!

We do `if (!file_exists($tokenFile))` to check if we need to clear the cache, but that function is covered by the cache in itself!
New PR incoming in a matter of minutes.

**Comment by Nyholm** [comment]
But hm... We are checking if the credentials has expired in the `CacheProvider`

**Comment by jderusse** [comment]
good catch. Indeed, the official AWS SDK calls twice the same `file_get_content` method

**Comment by Jean85** [comment]
#903 ready for review.
