### ISSUE TITLE
validate extra keys sent in input

### ISSUE THREAD

**Issue by jderusse** [async-aws/aws#914]
When user mistake and adds extra keys to the input, nothing tell theme something goes wrong.

cf : https://github.com/symfony/symfony/pull/39839/files

**Comment by Nyholm** [comment]
Hm. 

That issue could be found with psalm/phpstan. One could also argue that this is the reason why you should always use objects instead of arrays. 

Im not sure we should add validation.

**Comment by jderusse** [comment]
agreed. Let's close this issue
