### ISSUE TITLE
 [S3]Undefined class constant 'OPTION_SEND_CHUNKED_BODY'

### ISSUE THREAD

**Issue by ludgourdon** [async-aws/aws#947]
Hi,
I've this error using async-aws/s3:1.7 on object upload.
SignerV4ForS3 class  use constant 'OPTION_SEND_CHUNKED_BODY' but it's missing in Configuration class.
Cheers.

**Comment by jderusse** [comment]
Indeed, this constant only exists in `async-aws/core` version 1.8
We should have updated the `s3` package to require this version, but we forgot this case.

Anyways, this should be fix in the next version, has we now require the 1.9 versions.
In the mean time, you can fix it by updating the `async-aws/core` package.

**Comment by Nyholm** [comment]
@ludgourdon Did it work when you updated to async-aws/core: 1.8?

**Comment by ludgourdon** [comment]
@Nyholm Yes it worked. Thanks.

**Comment by jderusse** [comment]
Closing as the new version of S3 will fix this issue.
