### ISSUE TITLE
Requesting "create log group" feature in CloudWatchLogs

### ISSUE THREAD

**Issue by diadras** [async-aws/aws#956]
I am hoping to use Async-AWS in the application I am building. I use CloudWatchLogs to migrate my logs from my MySQL database to CloudWatch. Because I programmatically create applications I automatically create groups in CWL. So far I have been able to, and am, using Async-AWS to list log groups and write events to them.

I have tried to write my own methods in the CloudWatchLogsClient.php but have been unsuccessful. Is it possible to request a "create logs" method?

**Comment by jderusse** [comment]
Hey thank you for this idea. 

We will be happy to add the new `CreateLogGroup` operation. 

Here is the documentation about adding a new operation: https://async-aws.com/contribute/generate.html#creating-a-new-client-operation

Don't hesitate to tell me if you need help.

**Comment by Nyholm** [comment]
This issue has been open for a few days. I added #957 to solve this one. If you need any more operations, feel free to run this command and generate more code. See https://async-aws.com/contribute/generate.html#creating-a-new-client-operation for details.
