### ISSUE TITLE
Template issue leads to documentation having the wrong use statement

### ISSUE THREAD

**Issue by chx** [async-aws/aws#984]
https://async-aws.com/clients/sqs.html

`use AsyncAws\SQS\SQSClient;`

wants to be

`use AsyncAws\Sqs\SqsClient;`

under "Usage" it is current. I looked into the source and decided my level of understanding is not high enough to contribute a fix:

`<pre><code class="language-php hljs">{{ clientFqcn|printHLJSUseStatement }}`

**Comment by Nyholm** [comment]
Oops. There are now 2 PRs fixing this issue =)

#985 and #986

**Comment by chx** [comment]
Oh is that the frontmatter stuff that Drupal picked as well last October? https://www.drupal.org/node/3087114 Fancy. I am not on D9.1 yet :) I personally would prefer the twig stuff but I am not a maintainer (I did write a lot of Drupal - twig integration though so I am heavily biased.)

Sorry. I should've looked deeper but didn't have time.

Thanks for the quick fix.
