### ISSUE TITLE
Handle json_encode failures properly

### ISSUE THREAD

**Issue by floriansemm** [async-aws/aws#993]
We had recently a problem with large items that should be saved in DynamoDB. The limitation of 400kb for a DynamoDB item forced us to compress the content with gzip. This leads to a problem in `PutItemInput` class (line 250): the class tries to `json_encode` the payload, which does not work with binary content. Because of that the client tries to send `false` instead of valid json. 

It took me some time to figure out what the actual problem was, because there is no client-side validation of the sent content. It would be good to check if the payload is a valid string, instead of sending invalid data to AWS and let them do the validation. As far as I see there several classes where this missing check could create an error.

**Comment by Nyholm** [comment]
Thank you for this issue. 

It is a design decision to not verify the input. We would like AWS to validate all data. Imagine if we validated the data and AWS expanded the number of accepted values, then you have to wait for the client to be updated and released before you can use it.

Hm.. You are referring to [this line](https://github.com/async-aws/aws/blob/c0fa8720bfee1c9dc0568580ebd52bf9f284282b/src/Service/DynamoDb/src/Input/PutItemInput.php#L250). Im not familiar with DynamoDB. Does it allow you to send gzipped values out of the box? ie, would it work if we didnt run `json_encode()` on your playload?

If so, we can try to detect if we should run `json_encode` or not.

**Comment by Nyholm** [comment]
Oh... no.. How did you gzip you values?

**Comment by floriansemm** [comment]
this was my first attempted with compressed data:
```php
 $compressedData = gzcompress('a lot of json', 9);
 $data = [
     'Item' => [
        'id' => [
            'S' => 'some-key'
        ],
        'value' => [
            'S' => $compressedData,
         ]
     ],
     'TableName' => 'table-name',
];
```
`json_encode` returns false in this case and the put-request was sent to AWS anyway with `false` as value. I would expect an exception from the client in the line you have linked, because `false` is not valid json and was cased by an "invalid argument" from the user.

To send my compressed data, I have add `base64_encode` after compression:
```php
$compressedData = gzcompress($rawData, 9);
$encoded = base64_encode($compressedData);
```

**Comment by Nyholm** [comment]
Oh, I understand now. 

I agree that we should throw an exception if the `json_encode` fails. That is a bit different from the "validate the requests" version I first thought of. 

Im happy with the PR @jderusse provided.
