### ISSUE TITLE
[Question] Route53 client implementation

### ISSUE THREAD

**Issue by misantron** [async-aws/aws#997]
It will be great to have AWS Route53 client implementation. May be just a basic functionality for MVP.
What do you think?
Thanks

**Comment by Nyholm** [comment]
That sounds like a great idea. 

Do you want to give a try to [generate a new client](https://async-aws.com/contribute/generate.html#creating-a-new-client)?

**Comment by misantron** [comment]
I'll try, thanks

**Comment by misantron** [comment]
#999
